/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutResourcesRouteImport } from './routes/_layout/resources'
import { Route as LayoutOrganizationsRouteImport } from './routes/_layout/organizations'
import { Route as LayoutOid4vciRouteImport } from './routes/_layout/oid4vci'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutApplicationsRouteImport } from './routes/_layout/applications'
import { Route as LayoutContentComponentIdRouteImport } from './routes/_layout/content/$componentId'
import { Route as LayoutAccountSecuritySigningInRouteImport } from './routes/_layout/account-security/signing-in'
import { Route as LayoutAccountSecurityLinkedAccountsRouteImport } from './routes/_layout/account-security/linked-accounts'
import { Route as LayoutAccountSecurityDeviceActivityRouteImport } from './routes/_layout/account-security/device-activity'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesRoute = LayoutResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationsRoute = LayoutOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOid4vciRoute = LayoutOid4vciRouteImport.update({
  id: '/oid4vci',
  path: '/oid4vci',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApplicationsRoute = LayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContentComponentIdRoute =
  LayoutContentComponentIdRouteImport.update({
    id: '/content/$componentId',
    path: '/content/$componentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccountSecuritySigningInRoute =
  LayoutAccountSecuritySigningInRouteImport.update({
    id: '/account-security/signing-in',
    path: '/account-security/signing-in',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccountSecurityLinkedAccountsRoute =
  LayoutAccountSecurityLinkedAccountsRouteImport.update({
    id: '/account-security/linked-accounts',
    path: '/account-security/linked-accounts',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAccountSecurityDeviceActivityRoute =
  LayoutAccountSecurityDeviceActivityRouteImport.update({
    id: '/account-security/device-activity',
    path: '/account-security/device-activity',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/applications': typeof LayoutApplicationsRoute
  '/groups': typeof LayoutGroupsRoute
  '/oid4vci': typeof LayoutOid4vciRoute
  '/organizations': typeof LayoutOrganizationsRoute
  '/resources': typeof LayoutResourcesRoute
  '/account-security/device-activity': typeof LayoutAccountSecurityDeviceActivityRoute
  '/account-security/linked-accounts': typeof LayoutAccountSecurityLinkedAccountsRoute
  '/account-security/signing-in': typeof LayoutAccountSecuritySigningInRoute
  '/content/$componentId': typeof LayoutContentComponentIdRoute
}
export interface FileRoutesByTo {
  '/applications': typeof LayoutApplicationsRoute
  '/groups': typeof LayoutGroupsRoute
  '/oid4vci': typeof LayoutOid4vciRoute
  '/organizations': typeof LayoutOrganizationsRoute
  '/resources': typeof LayoutResourcesRoute
  '/': typeof LayoutIndexRoute
  '/account-security/device-activity': typeof LayoutAccountSecurityDeviceActivityRoute
  '/account-security/linked-accounts': typeof LayoutAccountSecurityLinkedAccountsRoute
  '/account-security/signing-in': typeof LayoutAccountSecuritySigningInRoute
  '/content/$componentId': typeof LayoutContentComponentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/applications': typeof LayoutApplicationsRoute
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/oid4vci': typeof LayoutOid4vciRoute
  '/_layout/organizations': typeof LayoutOrganizationsRoute
  '/_layout/resources': typeof LayoutResourcesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account-security/device-activity': typeof LayoutAccountSecurityDeviceActivityRoute
  '/_layout/account-security/linked-accounts': typeof LayoutAccountSecurityLinkedAccountsRoute
  '/_layout/account-security/signing-in': typeof LayoutAccountSecuritySigningInRoute
  '/_layout/content/$componentId': typeof LayoutContentComponentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/groups'
    | '/oid4vci'
    | '/organizations'
    | '/resources'
    | '/account-security/device-activity'
    | '/account-security/linked-accounts'
    | '/account-security/signing-in'
    | '/content/$componentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/applications'
    | '/groups'
    | '/oid4vci'
    | '/organizations'
    | '/resources'
    | '/'
    | '/account-security/device-activity'
    | '/account-security/linked-accounts'
    | '/account-security/signing-in'
    | '/content/$componentId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/applications'
    | '/_layout/groups'
    | '/_layout/oid4vci'
    | '/_layout/organizations'
    | '/_layout/resources'
    | '/_layout/'
    | '/_layout/account-security/device-activity'
    | '/_layout/account-security/linked-accounts'
    | '/_layout/account-security/signing-in'
    | '/_layout/content/$componentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources': {
      id: '/_layout/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organizations': {
      id: '/_layout/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof LayoutOrganizationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/oid4vci': {
      id: '/_layout/oid4vci'
      path: '/oid4vci'
      fullPath: '/oid4vci'
      preLoaderRoute: typeof LayoutOid4vciRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/applications': {
      id: '/_layout/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof LayoutApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/content/$componentId': {
      id: '/_layout/content/$componentId'
      path: '/content/$componentId'
      fullPath: '/content/$componentId'
      preLoaderRoute: typeof LayoutContentComponentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account-security/signing-in': {
      id: '/_layout/account-security/signing-in'
      path: '/account-security/signing-in'
      fullPath: '/account-security/signing-in'
      preLoaderRoute: typeof LayoutAccountSecuritySigningInRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account-security/linked-accounts': {
      id: '/_layout/account-security/linked-accounts'
      path: '/account-security/linked-accounts'
      fullPath: '/account-security/linked-accounts'
      preLoaderRoute: typeof LayoutAccountSecurityLinkedAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account-security/device-activity': {
      id: '/_layout/account-security/device-activity'
      path: '/account-security/device-activity'
      fullPath: '/account-security/device-activity'
      preLoaderRoute: typeof LayoutAccountSecurityDeviceActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutApplicationsRoute: typeof LayoutApplicationsRoute
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutOid4vciRoute: typeof LayoutOid4vciRoute
  LayoutOrganizationsRoute: typeof LayoutOrganizationsRoute
  LayoutResourcesRoute: typeof LayoutResourcesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountSecurityDeviceActivityRoute: typeof LayoutAccountSecurityDeviceActivityRoute
  LayoutAccountSecurityLinkedAccountsRoute: typeof LayoutAccountSecurityLinkedAccountsRoute
  LayoutAccountSecuritySigningInRoute: typeof LayoutAccountSecuritySigningInRoute
  LayoutContentComponentIdRoute: typeof LayoutContentComponentIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutApplicationsRoute: LayoutApplicationsRoute,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutOid4vciRoute: LayoutOid4vciRoute,
  LayoutOrganizationsRoute: LayoutOrganizationsRoute,
  LayoutResourcesRoute: LayoutResourcesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAccountSecurityDeviceActivityRoute:
    LayoutAccountSecurityDeviceActivityRoute,
  LayoutAccountSecurityLinkedAccountsRoute:
    LayoutAccountSecurityLinkedAccountsRoute,
  LayoutAccountSecuritySigningInRoute: LayoutAccountSecuritySigningInRoute,
  LayoutContentComponentIdRoute: LayoutContentComponentIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
