/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as OnboardingInboxRouteImport } from './routes/onboarding/inbox'
import { Route as DashboardSidebarRouteImport } from './routes/_dashboard/_sidebar'
import { Route as DashboardFullpageRouteImport } from './routes/_dashboard/_fullpage'
import { Route as DashboardSidebarIndexRouteImport } from './routes/_dashboard/_sidebar/index'
import { Route as OnboardingInboxSuccessRouteImport } from './routes/onboarding/inbox/success'
import { Route as OnboardingInboxEmbedRouteImport } from './routes/onboarding/inbox/embed'
import { Route as DashboardSidebarIntegrationsRouteImport } from './routes/_dashboard/_sidebar/integrations'
import { Route as DashboardSidebarIntegrationsConnectRouteImport } from './routes/_dashboard/_sidebar/integrations/connect'
import { Route as DashboardSidebarIntegrationsConnectProviderIdRouteImport } from './routes/_dashboard/_sidebar/integrations/connect/$providerId'
import { Route as DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport } from './routes/_dashboard/_sidebar/integrations/$integrationId/update'
import { Route as DashboardSidebarEnvEnvironmentSlugWorkflowsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/workflows'
import { Route as DashboardSidebarEnvEnvironmentSlugWelcomeRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/welcome'
import { Route as DashboardSidebarEnvEnvironmentSlugWebhooksRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/webhooks'
import { Route as DashboardSidebarEnvEnvironmentSlugTranslationsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/translations'
import { Route as DashboardSidebarEnvEnvironmentSlugTopicsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/topics'
import { Route as DashboardSidebarEnvEnvironmentSlugSubscribersRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/subscribers'
import { Route as DashboardSidebarEnvEnvironmentSlugLayoutsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/layouts'
import { Route as DashboardSidebarEnvEnvironmentSlugEnvironmentsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/environments'
import { Route as DashboardSidebarEnvEnvironmentSlugContextsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/contexts'
import { Route as DashboardSidebarEnvEnvironmentSlugApiKeysRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/api-keys'
import { Route as DashboardSidebarEnvEnvironmentSlugAnalyticsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/analytics'
import { Route as DashboardSidebarEnvEnvironmentSlugActivityFeedRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/activity-feed'
import { Route as DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/workflows/templates'
import { Route as DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/workflows/create'
import { Route as DashboardSidebarEnvEnvironmentSlugWebhooksLogsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/webhooks/logs'
import { Route as DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/webhooks/event-catalog'
import { Route as DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/webhooks/endpoints'
import { Route as DashboardSidebarEnvEnvironmentSlugWebhooksActivityRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/webhooks/activity'
import { Route as DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/translations/settings'
import { Route as DashboardSidebarEnvEnvironmentSlugTopicsCreateRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/topics/create'
import { Route as DashboardSidebarEnvEnvironmentSlugSubscribersCreateRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/subscribers/create'
import { Route as DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/subscribers/$subscriberId'
import { Route as DashboardSidebarEnvEnvironmentSlugLayoutsCreateRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/layouts/create'
import { Route as DashboardSidebarEnvEnvironmentSlugContextsCreateRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/contexts/create'
import { Route as DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/activity/workflow-runs'
import { Route as DashboardSidebarEnvEnvironmentSlugActivityRequestsRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/activity/requests'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug'
import { Route as DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/layouts/$layoutSlug'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/index'
import { Route as DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/workflows/templates/$templateId'
import { Route as DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/workflows/duplicate/$workflowId'
import { Route as DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/topics/$topicKey/edit'
import { Route as DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/layouts/duplicate/$layoutId'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/trigger'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/test'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/preferences'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/activity'
import { Route as DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
import { Route as DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRouteImport } from './routes/_dashboard/_sidebar/env/$environmentSlug/contexts/$type/$id/edit'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/index'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
import { Route as DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport } from './routes/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInboxRoute = OnboardingInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OnboardingRoute,
} as any)
const DashboardSidebarRoute = DashboardSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFullpageRoute = DashboardFullpageRouteImport.update({
  id: '/_fullpage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSidebarIndexRoute = DashboardSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSidebarRoute,
} as any)
const OnboardingInboxSuccessRoute = OnboardingInboxSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingInboxRoute,
} as any)
const OnboardingInboxEmbedRoute = OnboardingInboxEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => OnboardingInboxRoute,
} as any)
const DashboardSidebarIntegrationsRoute =
  DashboardSidebarIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarIntegrationsConnectRoute =
  DashboardSidebarIntegrationsConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => DashboardSidebarIntegrationsRoute,
  } as any)
const DashboardSidebarIntegrationsConnectProviderIdRoute =
  DashboardSidebarIntegrationsConnectProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => DashboardSidebarIntegrationsConnectRoute,
  } as any)
const DashboardSidebarIntegrationsIntegrationIdUpdateRoute =
  DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport.update({
    id: '/$integrationId/update',
    path: '/$integrationId/update',
    getParentRoute: () => DashboardSidebarIntegrationsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWorkflowsRoute =
  DashboardSidebarEnvEnvironmentSlugWorkflowsRouteImport.update({
    id: '/env/$environmentSlug/workflows',
    path: '/env/$environmentSlug/workflows',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWelcomeRoute =
  DashboardSidebarEnvEnvironmentSlugWelcomeRouteImport.update({
    id: '/env/$environmentSlug/welcome',
    path: '/env/$environmentSlug/welcome',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWebhooksRoute =
  DashboardSidebarEnvEnvironmentSlugWebhooksRouteImport.update({
    id: '/env/$environmentSlug/webhooks',
    path: '/env/$environmentSlug/webhooks',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugTranslationsRoute =
  DashboardSidebarEnvEnvironmentSlugTranslationsRouteImport.update({
    id: '/env/$environmentSlug/translations',
    path: '/env/$environmentSlug/translations',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugTopicsRoute =
  DashboardSidebarEnvEnvironmentSlugTopicsRouteImport.update({
    id: '/env/$environmentSlug/topics',
    path: '/env/$environmentSlug/topics',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugSubscribersRoute =
  DashboardSidebarEnvEnvironmentSlugSubscribersRouteImport.update({
    id: '/env/$environmentSlug/subscribers',
    path: '/env/$environmentSlug/subscribers',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugLayoutsRoute =
  DashboardSidebarEnvEnvironmentSlugLayoutsRouteImport.update({
    id: '/env/$environmentSlug/layouts',
    path: '/env/$environmentSlug/layouts',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute =
  DashboardSidebarEnvEnvironmentSlugEnvironmentsRouteImport.update({
    id: '/env/$environmentSlug/environments',
    path: '/env/$environmentSlug/environments',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugContextsRoute =
  DashboardSidebarEnvEnvironmentSlugContextsRouteImport.update({
    id: '/env/$environmentSlug/contexts',
    path: '/env/$environmentSlug/contexts',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugApiKeysRoute =
  DashboardSidebarEnvEnvironmentSlugApiKeysRouteImport.update({
    id: '/env/$environmentSlug/api-keys',
    path: '/env/$environmentSlug/api-keys',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugAnalyticsRoute =
  DashboardSidebarEnvEnvironmentSlugAnalyticsRouteImport.update({
    id: '/env/$environmentSlug/analytics',
    path: '/env/$environmentSlug/analytics',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugActivityFeedRoute =
  DashboardSidebarEnvEnvironmentSlugActivityFeedRouteImport.update({
    id: '/env/$environmentSlug/activity-feed',
    path: '/env/$environmentSlug/activity-feed',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute =
  DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWorkflowsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute =
  DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWorkflowsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute =
  DashboardSidebarEnvEnvironmentSlugWebhooksLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute =
  DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRouteImport.update({
    id: '/event-catalog',
    path: '/event-catalog',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute =
  DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute =
  DashboardSidebarEnvEnvironmentSlugWebhooksActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute =
  DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugTranslationsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute =
  DashboardSidebarEnvEnvironmentSlugTopicsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugTopicsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute =
  DashboardSidebarEnvEnvironmentSlugSubscribersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugSubscribersRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute =
  DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRouteImport.update({
    id: '/$subscriberId',
    path: '/$subscriberId',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugSubscribersRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute =
  DashboardSidebarEnvEnvironmentSlugLayoutsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugLayoutsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugContextsCreateRoute =
  DashboardSidebarEnvEnvironmentSlugContextsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugContextsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute =
  DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRouteImport.update({
    id: '/env/$environmentSlug/activity/workflow-runs',
    path: '/env/$environmentSlug/activity/workflow-runs',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute =
  DashboardSidebarEnvEnvironmentSlugActivityRequestsRouteImport.update({
    id: '/env/$environmentSlug/activity/requests',
    path: '/env/$environmentSlug/activity/requests',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteImport.update({
    id: '/env/$environmentSlug/workflows/$workflowSlug',
    path: '/env/$environmentSlug/workflows/$workflowSlug',
    getParentRoute: () => DashboardFullpageRoute,
  } as any)
const DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute =
  DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRouteImport.update({
    id: '/env/$environmentSlug/layouts/$layoutSlug',
    path: '/env/$environmentSlug/layouts/$layoutSlug',
    getParentRoute: () => DashboardFullpageRoute,
  } as any)
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute =
  DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport.update(
    {
      id: '/$templateId',
      path: '/$templateId',
      getParentRoute: () =>
        DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute,
    } as any,
  )
const DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute =
  DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport.update(
    {
      id: '/duplicate/$workflowId',
      path: '/duplicate/$workflowId',
      getParentRoute: () => DashboardSidebarEnvEnvironmentSlugWorkflowsRoute,
    } as any,
  )
const DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute =
  DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRouteImport.update({
    id: '/$topicKey/edit',
    path: '/$topicKey/edit',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugTopicsRoute,
  } as any)
const DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute =
  DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport.update({
    id: '/duplicate/$layoutId',
    path: '/duplicate/$layoutId',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugLayoutsRoute,
  } as any)
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport.update(
    {
      id: '/trigger',
      path: '/trigger',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport.update(
    {
      id: '/test',
      path: '/test',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport.update(
    {
      id: '/preferences',
      path: '/preferences',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport.update(
    {
      id: '/activity',
      path: '/activity',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute =
  DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport.update(
    {
      id: '/$resourceType/$resourceId/$locale',
      path: '/$resourceType/$resourceId/$locale',
      getParentRoute: () => DashboardSidebarEnvEnvironmentSlugTranslationsRoute,
    } as any,
  )
const DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute =
  DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRouteImport.update({
    id: '/$type/$id/edit',
    path: '/$type/$id/edit',
    getParentRoute: () => DashboardSidebarEnvEnvironmentSlugContextsRoute,
  } as any)
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport.update(
    {
      id: '/steps/$stepSlug/',
      path: '/steps/$stepSlug/',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport.update(
    {
      id: '/steps/$stepSlug/editor',
      path: '/steps/$stepSlug/editor',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport.update(
    {
      id: '/steps/$stepSlug/conditions',
      path: '/steps/$stepSlug/conditions',
      getParentRoute: () =>
        DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DashboardSidebarIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/env/$environmentSlug/activity-feed': typeof DashboardSidebarEnvEnvironmentSlugActivityFeedRoute
  '/env/$environmentSlug/analytics': typeof DashboardSidebarEnvEnvironmentSlugAnalyticsRoute
  '/env/$environmentSlug/api-keys': typeof DashboardSidebarEnvEnvironmentSlugApiKeysRoute
  '/env/$environmentSlug/contexts': typeof DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren
  '/env/$environmentSlug/environments': typeof DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute
  '/env/$environmentSlug/layouts': typeof DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren
  '/env/$environmentSlug/subscribers': typeof DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren
  '/env/$environmentSlug/topics': typeof DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren
  '/env/$environmentSlug/translations': typeof DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren
  '/env/$environmentSlug/webhooks': typeof DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren
  '/env/$environmentSlug/welcome': typeof DashboardSidebarEnvEnvironmentSlugWelcomeRoute
  '/env/$environmentSlug/workflows': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren
  '/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/env/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute
  '/env/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
  '/env/$environmentSlug/activity/requests': typeof DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute
  '/env/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute
  '/env/$environmentSlug/contexts/create': typeof DashboardSidebarEnvEnvironmentSlugContextsCreateRoute
  '/env/$environmentSlug/layouts/create': typeof DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute
  '/env/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute
  '/env/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute
  '/env/$environmentSlug/topics/create': typeof DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute
  '/env/$environmentSlug/translations/settings': typeof DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute
  '/env/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute
  '/env/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute
  '/env/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute
  '/env/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute
  '/env/$environmentSlug/workflows/create': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute
  '/env/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/env/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/env/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/env/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/env/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/env/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/env/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute
  '/env/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/env/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/env/$environmentSlug/workflows/$workflowSlug/': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/env/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute
  '/env/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardSidebarIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/env/$environmentSlug/activity-feed': typeof DashboardSidebarEnvEnvironmentSlugActivityFeedRoute
  '/env/$environmentSlug/analytics': typeof DashboardSidebarEnvEnvironmentSlugAnalyticsRoute
  '/env/$environmentSlug/api-keys': typeof DashboardSidebarEnvEnvironmentSlugApiKeysRoute
  '/env/$environmentSlug/contexts': typeof DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren
  '/env/$environmentSlug/environments': typeof DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute
  '/env/$environmentSlug/layouts': typeof DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren
  '/env/$environmentSlug/subscribers': typeof DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren
  '/env/$environmentSlug/topics': typeof DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren
  '/env/$environmentSlug/translations': typeof DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren
  '/env/$environmentSlug/webhooks': typeof DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren
  '/env/$environmentSlug/welcome': typeof DashboardSidebarEnvEnvironmentSlugWelcomeRoute
  '/env/$environmentSlug/workflows': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren
  '/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/env/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute
  '/env/$environmentSlug/activity/requests': typeof DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute
  '/env/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute
  '/env/$environmentSlug/contexts/create': typeof DashboardSidebarEnvEnvironmentSlugContextsCreateRoute
  '/env/$environmentSlug/layouts/create': typeof DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute
  '/env/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute
  '/env/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute
  '/env/$environmentSlug/topics/create': typeof DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute
  '/env/$environmentSlug/translations/settings': typeof DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute
  '/env/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute
  '/env/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute
  '/env/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute
  '/env/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute
  '/env/$environmentSlug/workflows/create': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute
  '/env/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/env/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/env/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/env/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/env/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/env/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/env/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute
  '/env/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/env/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/env/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/env/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute
  '/env/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_dashboard/_fullpage': typeof DashboardFullpageRouteWithChildren
  '/_dashboard/_sidebar': typeof DashboardSidebarRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/_dashboard/_sidebar/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/_dashboard/_sidebar/': typeof DashboardSidebarIndexRoute
  '/_dashboard/_sidebar/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/activity-feed': typeof DashboardSidebarEnvEnvironmentSlugActivityFeedRoute
  '/_dashboard/_sidebar/env/$environmentSlug/analytics': typeof DashboardSidebarEnvEnvironmentSlugAnalyticsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/api-keys': typeof DashboardSidebarEnvEnvironmentSlugApiKeysRoute
  '/_dashboard/_sidebar/env/$environmentSlug/contexts': typeof DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/environments': typeof DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/layouts': typeof DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/subscribers': typeof DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/topics': typeof DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/translations': typeof DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/webhooks': typeof DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/welcome': typeof DashboardSidebarEnvEnvironmentSlugWelcomeRoute
  '/_dashboard/_sidebar/env/$environmentSlug/workflows': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren
  '/_dashboard/_sidebar/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/_dashboard/_sidebar/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/_dashboard/_fullpage/env/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
  '/_dashboard/_sidebar/env/$environmentSlug/activity/requests': typeof DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/contexts/create': typeof DashboardSidebarEnvEnvironmentSlugContextsCreateRoute
  '/_dashboard/_sidebar/env/$environmentSlug/layouts/create': typeof DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute
  '/_dashboard/_sidebar/env/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute
  '/_dashboard/_sidebar/env/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute
  '/_dashboard/_sidebar/env/$environmentSlug/topics/create': typeof DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute
  '/_dashboard/_sidebar/env/$environmentSlug/translations/settings': typeof DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute
  '/_dashboard/_sidebar/env/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute
  '/_dashboard/_sidebar/env/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute
  '/_dashboard/_sidebar/env/$environmentSlug/workflows/create': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute
  '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/_dashboard/_sidebar/env/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/_dashboard/_sidebar/env/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute
  '/_dashboard/_sidebar/env/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/_dashboard/_sidebar/env/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute
  '/_dashboard/_sidebar/env/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/onboarding/inbox'
    | '/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/integrations/connect'
    | '/env/$environmentSlug/activity-feed'
    | '/env/$environmentSlug/analytics'
    | '/env/$environmentSlug/api-keys'
    | '/env/$environmentSlug/contexts'
    | '/env/$environmentSlug/environments'
    | '/env/$environmentSlug/layouts'
    | '/env/$environmentSlug/subscribers'
    | '/env/$environmentSlug/topics'
    | '/env/$environmentSlug/translations'
    | '/env/$environmentSlug/webhooks'
    | '/env/$environmentSlug/welcome'
    | '/env/$environmentSlug/workflows'
    | '/integrations/$integrationId/update'
    | '/integrations/connect/$providerId'
    | '/env/$environmentSlug/layouts/$layoutSlug'
    | '/env/$environmentSlug/workflows/$workflowSlug'
    | '/env/$environmentSlug/activity/requests'
    | '/env/$environmentSlug/activity/workflow-runs'
    | '/env/$environmentSlug/contexts/create'
    | '/env/$environmentSlug/layouts/create'
    | '/env/$environmentSlug/subscribers/$subscriberId'
    | '/env/$environmentSlug/subscribers/create'
    | '/env/$environmentSlug/topics/create'
    | '/env/$environmentSlug/translations/settings'
    | '/env/$environmentSlug/webhooks/activity'
    | '/env/$environmentSlug/webhooks/endpoints'
    | '/env/$environmentSlug/webhooks/event-catalog'
    | '/env/$environmentSlug/webhooks/logs'
    | '/env/$environmentSlug/workflows/create'
    | '/env/$environmentSlug/workflows/templates'
    | '/env/$environmentSlug/workflows/$workflowSlug/activity'
    | '/env/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/env/$environmentSlug/workflows/$workflowSlug/test'
    | '/env/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/env/$environmentSlug/layouts/duplicate/$layoutId'
    | '/env/$environmentSlug/topics/$topicKey/edit'
    | '/env/$environmentSlug/workflows/duplicate/$workflowId'
    | '/env/$environmentSlug/workflows/templates/$templateId'
    | '/env/$environmentSlug/workflows/$workflowSlug/'
    | '/env/$environmentSlug/contexts/$type/$id/edit'
    | '/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/onboarding/inbox'
    | '/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/integrations/connect'
    | '/env/$environmentSlug/activity-feed'
    | '/env/$environmentSlug/analytics'
    | '/env/$environmentSlug/api-keys'
    | '/env/$environmentSlug/contexts'
    | '/env/$environmentSlug/environments'
    | '/env/$environmentSlug/layouts'
    | '/env/$environmentSlug/subscribers'
    | '/env/$environmentSlug/topics'
    | '/env/$environmentSlug/translations'
    | '/env/$environmentSlug/webhooks'
    | '/env/$environmentSlug/welcome'
    | '/env/$environmentSlug/workflows'
    | '/integrations/$integrationId/update'
    | '/integrations/connect/$providerId'
    | '/env/$environmentSlug/layouts/$layoutSlug'
    | '/env/$environmentSlug/activity/requests'
    | '/env/$environmentSlug/activity/workflow-runs'
    | '/env/$environmentSlug/contexts/create'
    | '/env/$environmentSlug/layouts/create'
    | '/env/$environmentSlug/subscribers/$subscriberId'
    | '/env/$environmentSlug/subscribers/create'
    | '/env/$environmentSlug/topics/create'
    | '/env/$environmentSlug/translations/settings'
    | '/env/$environmentSlug/webhooks/activity'
    | '/env/$environmentSlug/webhooks/endpoints'
    | '/env/$environmentSlug/webhooks/event-catalog'
    | '/env/$environmentSlug/webhooks/logs'
    | '/env/$environmentSlug/workflows/create'
    | '/env/$environmentSlug/workflows/templates'
    | '/env/$environmentSlug/workflows/$workflowSlug/activity'
    | '/env/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/env/$environmentSlug/workflows/$workflowSlug/test'
    | '/env/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/env/$environmentSlug/layouts/duplicate/$layoutId'
    | '/env/$environmentSlug/topics/$topicKey/edit'
    | '/env/$environmentSlug/workflows/duplicate/$workflowId'
    | '/env/$environmentSlug/workflows/templates/$templateId'
    | '/env/$environmentSlug/workflows/$workflowSlug'
    | '/env/$environmentSlug/contexts/$type/$id/edit'
    | '/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug'
  id:
    | '__root__'
    | '/_dashboard'
    | '/onboarding'
    | '/_dashboard/_fullpage'
    | '/_dashboard/_sidebar'
    | '/onboarding/inbox'
    | '/_dashboard/_sidebar/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/_dashboard/_sidebar/'
    | '/_dashboard/_sidebar/integrations/connect'
    | '/_dashboard/_sidebar/env/$environmentSlug/activity-feed'
    | '/_dashboard/_sidebar/env/$environmentSlug/analytics'
    | '/_dashboard/_sidebar/env/$environmentSlug/api-keys'
    | '/_dashboard/_sidebar/env/$environmentSlug/contexts'
    | '/_dashboard/_sidebar/env/$environmentSlug/environments'
    | '/_dashboard/_sidebar/env/$environmentSlug/layouts'
    | '/_dashboard/_sidebar/env/$environmentSlug/subscribers'
    | '/_dashboard/_sidebar/env/$environmentSlug/topics'
    | '/_dashboard/_sidebar/env/$environmentSlug/translations'
    | '/_dashboard/_sidebar/env/$environmentSlug/webhooks'
    | '/_dashboard/_sidebar/env/$environmentSlug/welcome'
    | '/_dashboard/_sidebar/env/$environmentSlug/workflows'
    | '/_dashboard/_sidebar/integrations/$integrationId/update'
    | '/_dashboard/_sidebar/integrations/connect/$providerId'
    | '/_dashboard/_fullpage/env/$environmentSlug/layouts/$layoutSlug'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug'
    | '/_dashboard/_sidebar/env/$environmentSlug/activity/requests'
    | '/_dashboard/_sidebar/env/$environmentSlug/activity/workflow-runs'
    | '/_dashboard/_sidebar/env/$environmentSlug/contexts/create'
    | '/_dashboard/_sidebar/env/$environmentSlug/layouts/create'
    | '/_dashboard/_sidebar/env/$environmentSlug/subscribers/$subscriberId'
    | '/_dashboard/_sidebar/env/$environmentSlug/subscribers/create'
    | '/_dashboard/_sidebar/env/$environmentSlug/topics/create'
    | '/_dashboard/_sidebar/env/$environmentSlug/translations/settings'
    | '/_dashboard/_sidebar/env/$environmentSlug/webhooks/activity'
    | '/_dashboard/_sidebar/env/$environmentSlug/webhooks/endpoints'
    | '/_dashboard/_sidebar/env/$environmentSlug/webhooks/event-catalog'
    | '/_dashboard/_sidebar/env/$environmentSlug/webhooks/logs'
    | '/_dashboard/_sidebar/env/$environmentSlug/workflows/create'
    | '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/activity'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/test'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/_dashboard/_sidebar/env/$environmentSlug/layouts/duplicate/$layoutId'
    | '/_dashboard/_sidebar/env/$environmentSlug/topics/$topicKey/edit'
    | '/_dashboard/_sidebar/env/$environmentSlug/workflows/duplicate/$workflowId'
    | '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates/$templateId'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/'
    | '/_dashboard/_sidebar/env/$environmentSlug/contexts/$type/$id/edit'
    | '/_dashboard/_sidebar/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/inbox': {
      id: '/onboarding/inbox'
      path: '/inbox'
      fullPath: '/onboarding/inbox'
      preLoaderRoute: typeof OnboardingInboxRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_dashboard/_sidebar': {
      id: '/_dashboard/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardSidebarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_fullpage': {
      id: '/_dashboard/_fullpage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardFullpageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_sidebar/': {
      id: '/_dashboard/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardSidebarIndexRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/onboarding/inbox/success': {
      id: '/onboarding/inbox/success'
      path: '/success'
      fullPath: '/onboarding/inbox/success'
      preLoaderRoute: typeof OnboardingInboxSuccessRouteImport
      parentRoute: typeof OnboardingInboxRoute
    }
    '/onboarding/inbox/embed': {
      id: '/onboarding/inbox/embed'
      path: '/embed'
      fullPath: '/onboarding/inbox/embed'
      preLoaderRoute: typeof OnboardingInboxEmbedRouteImport
      parentRoute: typeof OnboardingInboxRoute
    }
    '/_dashboard/_sidebar/integrations': {
      id: '/_dashboard/_sidebar/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardSidebarIntegrationsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/integrations/connect': {
      id: '/_dashboard/_sidebar/integrations/connect'
      path: '/connect'
      fullPath: '/integrations/connect'
      preLoaderRoute: typeof DashboardSidebarIntegrationsConnectRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsRoute
    }
    '/_dashboard/_sidebar/integrations/connect/$providerId': {
      id: '/_dashboard/_sidebar/integrations/connect/$providerId'
      path: '/$providerId'
      fullPath: '/integrations/connect/$providerId'
      preLoaderRoute: typeof DashboardSidebarIntegrationsConnectProviderIdRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsConnectRoute
    }
    '/_dashboard/_sidebar/integrations/$integrationId/update': {
      id: '/_dashboard/_sidebar/integrations/$integrationId/update'
      path: '/$integrationId/update'
      fullPath: '/integrations/$integrationId/update'
      preLoaderRoute: typeof DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/workflows': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/workflows'
      path: '/env/$environmentSlug/workflows'
      fullPath: '/env/$environmentSlug/workflows'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/welcome': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/welcome'
      path: '/env/$environmentSlug/welcome'
      fullPath: '/env/$environmentSlug/welcome'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWelcomeRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/webhooks': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/webhooks'
      path: '/env/$environmentSlug/webhooks'
      fullPath: '/env/$environmentSlug/webhooks'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/translations': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/translations'
      path: '/env/$environmentSlug/translations'
      fullPath: '/env/$environmentSlug/translations'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/topics': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/topics'
      path: '/env/$environmentSlug/topics'
      fullPath: '/env/$environmentSlug/topics'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/subscribers': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/subscribers'
      path: '/env/$environmentSlug/subscribers'
      fullPath: '/env/$environmentSlug/subscribers'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/layouts': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/layouts'
      path: '/env/$environmentSlug/layouts'
      fullPath: '/env/$environmentSlug/layouts'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/environments': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/environments'
      path: '/env/$environmentSlug/environments'
      fullPath: '/env/$environmentSlug/environments'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugEnvironmentsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/contexts': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/contexts'
      path: '/env/$environmentSlug/contexts'
      fullPath: '/env/$environmentSlug/contexts'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/api-keys': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/api-keys'
      path: '/env/$environmentSlug/api-keys'
      fullPath: '/env/$environmentSlug/api-keys'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugApiKeysRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/analytics': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/analytics'
      path: '/env/$environmentSlug/analytics'
      fullPath: '/env/$environmentSlug/analytics'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugAnalyticsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/activity-feed': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/activity-feed'
      path: '/env/$environmentSlug/activity-feed'
      fullPath: '/env/$environmentSlug/activity-feed'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityFeedRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates'
      path: '/templates'
      fullPath: '/env/$environmentSlug/workflows/templates'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/workflows/create': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/workflows/create'
      path: '/create'
      fullPath: '/env/$environmentSlug/workflows/create'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/webhooks/logs': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/webhooks/logs'
      path: '/logs'
      fullPath: '/env/$environmentSlug/webhooks/logs'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksLogsRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/webhooks/event-catalog': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/webhooks/event-catalog'
      path: '/event-catalog'
      fullPath: '/env/$environmentSlug/webhooks/event-catalog'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/webhooks/endpoints': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/webhooks/endpoints'
      path: '/endpoints'
      fullPath: '/env/$environmentSlug/webhooks/endpoints'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/webhooks/activity': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/webhooks/activity'
      path: '/activity'
      fullPath: '/env/$environmentSlug/webhooks/activity'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksActivityRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/translations/settings': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/translations/settings'
      path: '/settings'
      fullPath: '/env/$environmentSlug/translations/settings'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/topics/create': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/topics/create'
      path: '/create'
      fullPath: '/env/$environmentSlug/topics/create'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/subscribers/create': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/subscribers/create'
      path: '/create'
      fullPath: '/env/$environmentSlug/subscribers/create'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/subscribers/$subscriberId': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/subscribers/$subscriberId'
      path: '/$subscriberId'
      fullPath: '/env/$environmentSlug/subscribers/$subscriberId'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/layouts/create': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/layouts/create'
      path: '/create'
      fullPath: '/env/$environmentSlug/layouts/create'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/contexts/create': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/contexts/create'
      path: '/create'
      fullPath: '/env/$environmentSlug/contexts/create'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/activity/workflow-runs': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/activity/workflow-runs'
      path: '/env/$environmentSlug/activity/workflow-runs'
      fullPath: '/env/$environmentSlug/activity/workflow-runs'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/activity/requests': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/activity/requests'
      path: '/env/$environmentSlug/activity/requests'
      fullPath: '/env/$environmentSlug/activity/requests'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityRequestsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug'
      path: '/env/$environmentSlug/workflows/$workflowSlug'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteImport
      parentRoute: typeof DashboardFullpageRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/layouts/$layoutSlug': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/layouts/$layoutSlug'
      path: '/env/$environmentSlug/layouts/$layoutSlug'
      fullPath: '/env/$environmentSlug/layouts/$layoutSlug'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRouteImport
      parentRoute: typeof DashboardFullpageRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/'
      path: '/'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates/$templateId': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/workflows/templates/$templateId'
      path: '/$templateId'
      fullPath: '/env/$environmentSlug/workflows/templates/$templateId'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/workflows/duplicate/$workflowId': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/workflows/duplicate/$workflowId'
      path: '/duplicate/$workflowId'
      fullPath: '/env/$environmentSlug/workflows/duplicate/$workflowId'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/topics/$topicKey/edit': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/topics/$topicKey/edit'
      path: '/$topicKey/edit'
      fullPath: '/env/$environmentSlug/topics/$topicKey/edit'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/layouts/duplicate/$layoutId': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/layouts/duplicate/$layoutId'
      path: '/duplicate/$layoutId'
      fullPath: '/env/$environmentSlug/layouts/duplicate/$layoutId'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/trigger': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/trigger'
      path: '/trigger'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/trigger'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/test': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/test'
      path: '/test'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/test'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/preferences': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/preferences'
      path: '/preferences'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/preferences'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/activity': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/activity'
      path: '/activity'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/activity'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/translations/$resourceType/$resourceId/$locale': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
      path: '/$resourceType/$resourceId/$locale'
      fullPath: '/env/$environmentSlug/translations/$resourceType/$resourceId/$locale'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsRoute
    }
    '/_dashboard/_sidebar/env/$environmentSlug/contexts/$type/$id/edit': {
      id: '/_dashboard/_sidebar/env/$environmentSlug/contexts/$type/$id/edit'
      path: '/$type/$id/edit'
      fullPath: '/env/$environmentSlug/contexts/$type/$id/edit'
      preLoaderRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRouteImport
      parentRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
      path: '/steps/$stepSlug'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
      path: '/steps/$stepSlug/editor'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': {
      id: '/_dashboard/_fullpage/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
      path: '/steps/$stepSlug/conditions'
      fullPath: '/env/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
      preLoaderRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport
      parentRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
  }
}

interface DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteChildren {
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}

const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteChildren: DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteChildren =
  {
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugActivityRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTestRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugIndexRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute,
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute:
      DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute,
  }

const DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren =
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute._addFileChildren(
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteChildren,
  )

interface DashboardFullpageRouteChildren {
  DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute: typeof DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute: typeof DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
}

const DashboardFullpageRouteChildren: DashboardFullpageRouteChildren = {
  DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute:
    DashboardFullpageEnvEnvironmentSlugLayoutsLayoutSlugRoute,
  DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRoute:
    DashboardFullpageEnvEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren,
}

const DashboardFullpageRouteWithChildren =
  DashboardFullpageRoute._addFileChildren(DashboardFullpageRouteChildren)

interface DashboardSidebarIntegrationsConnectRouteChildren {
  DashboardSidebarIntegrationsConnectProviderIdRoute: typeof DashboardSidebarIntegrationsConnectProviderIdRoute
}

const DashboardSidebarIntegrationsConnectRouteChildren: DashboardSidebarIntegrationsConnectRouteChildren =
  {
    DashboardSidebarIntegrationsConnectProviderIdRoute:
      DashboardSidebarIntegrationsConnectProviderIdRoute,
  }

const DashboardSidebarIntegrationsConnectRouteWithChildren =
  DashboardSidebarIntegrationsConnectRoute._addFileChildren(
    DashboardSidebarIntegrationsConnectRouteChildren,
  )

interface DashboardSidebarIntegrationsRouteChildren {
  DashboardSidebarIntegrationsConnectRoute: typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  DashboardSidebarIntegrationsIntegrationIdUpdateRoute: typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
}

const DashboardSidebarIntegrationsRouteChildren: DashboardSidebarIntegrationsRouteChildren =
  {
    DashboardSidebarIntegrationsConnectRoute:
      DashboardSidebarIntegrationsConnectRouteWithChildren,
    DashboardSidebarIntegrationsIntegrationIdUpdateRoute:
      DashboardSidebarIntegrationsIntegrationIdUpdateRoute,
  }

const DashboardSidebarIntegrationsRouteWithChildren =
  DashboardSidebarIntegrationsRoute._addFileChildren(
    DashboardSidebarIntegrationsRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugContextsRouteChildren {
  DashboardSidebarEnvEnvironmentSlugContextsCreateRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsCreateRoute
  DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute
}

const DashboardSidebarEnvEnvironmentSlugContextsRouteChildren: DashboardSidebarEnvEnvironmentSlugContextsRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugContextsCreateRoute:
      DashboardSidebarEnvEnvironmentSlugContextsCreateRoute,
    DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute:
      DashboardSidebarEnvEnvironmentSlugContextsTypeIdEditRoute,
  }

const DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugContextsRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugContextsRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugLayoutsRouteChildren {
  DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute
  DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute
}

const DashboardSidebarEnvEnvironmentSlugLayoutsRouteChildren: DashboardSidebarEnvEnvironmentSlugLayoutsRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute:
      DashboardSidebarEnvEnvironmentSlugLayoutsCreateRoute,
    DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute:
      DashboardSidebarEnvEnvironmentSlugLayoutsDuplicateLayoutIdRoute,
  }

const DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugLayoutsRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugLayoutsRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugSubscribersRouteChildren {
  DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute
  DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute
}

const DashboardSidebarEnvEnvironmentSlugSubscribersRouteChildren: DashboardSidebarEnvEnvironmentSlugSubscribersRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute:
      DashboardSidebarEnvEnvironmentSlugSubscribersSubscriberIdRoute,
    DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute:
      DashboardSidebarEnvEnvironmentSlugSubscribersCreateRoute,
  }

const DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugSubscribersRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugSubscribersRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugTopicsRouteChildren {
  DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute
  DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute
}

const DashboardSidebarEnvEnvironmentSlugTopicsRouteChildren: DashboardSidebarEnvEnvironmentSlugTopicsRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute:
      DashboardSidebarEnvEnvironmentSlugTopicsCreateRoute,
    DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute:
      DashboardSidebarEnvEnvironmentSlugTopicsTopicKeyEditRoute,
  }

const DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugTopicsRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugTopicsRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugTranslationsRouteChildren {
  DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute
  DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
}

const DashboardSidebarEnvEnvironmentSlugTranslationsRouteChildren: DashboardSidebarEnvEnvironmentSlugTranslationsRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute:
      DashboardSidebarEnvEnvironmentSlugTranslationsSettingsRoute,
    DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute:
      DashboardSidebarEnvEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute,
  }

const DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugTranslationsRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugTranslationsRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugWebhooksRouteChildren {
  DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute
  DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute
  DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute
  DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute
}

const DashboardSidebarEnvEnvironmentSlugWebhooksRouteChildren: DashboardSidebarEnvEnvironmentSlugWebhooksRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute:
      DashboardSidebarEnvEnvironmentSlugWebhooksActivityRoute,
    DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute:
      DashboardSidebarEnvEnvironmentSlugWebhooksEndpointsRoute,
    DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute:
      DashboardSidebarEnvEnvironmentSlugWebhooksEventCatalogRoute,
    DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute:
      DashboardSidebarEnvEnvironmentSlugWebhooksLogsRoute,
  }

const DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugWebhooksRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugWebhooksRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteChildren {
  DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
}

const DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteChildren: DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute:
      DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesTemplateIdRoute,
  }

const DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteChildren,
  )

interface DashboardSidebarEnvEnvironmentSlugWorkflowsRouteChildren {
  DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute
  DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
}

const DashboardSidebarEnvEnvironmentSlugWorkflowsRouteChildren: DashboardSidebarEnvEnvironmentSlugWorkflowsRouteChildren =
  {
    DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute:
      DashboardSidebarEnvEnvironmentSlugWorkflowsCreateRoute,
    DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRoute:
      DashboardSidebarEnvEnvironmentSlugWorkflowsTemplatesRouteWithChildren,
    DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute:
      DashboardSidebarEnvEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute,
  }

const DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren =
  DashboardSidebarEnvEnvironmentSlugWorkflowsRoute._addFileChildren(
    DashboardSidebarEnvEnvironmentSlugWorkflowsRouteChildren,
  )

interface DashboardSidebarRouteChildren {
  DashboardSidebarIntegrationsRoute: typeof DashboardSidebarIntegrationsRouteWithChildren
  DashboardSidebarIndexRoute: typeof DashboardSidebarIndexRoute
  DashboardSidebarEnvEnvironmentSlugActivityFeedRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityFeedRoute
  DashboardSidebarEnvEnvironmentSlugAnalyticsRoute: typeof DashboardSidebarEnvEnvironmentSlugAnalyticsRoute
  DashboardSidebarEnvEnvironmentSlugApiKeysRoute: typeof DashboardSidebarEnvEnvironmentSlugApiKeysRoute
  DashboardSidebarEnvEnvironmentSlugContextsRoute: typeof DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute: typeof DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute
  DashboardSidebarEnvEnvironmentSlugLayoutsRoute: typeof DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugSubscribersRoute: typeof DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugTopicsRoute: typeof DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugTranslationsRoute: typeof DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugWebhooksRoute: typeof DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugWelcomeRoute: typeof DashboardSidebarEnvEnvironmentSlugWelcomeRoute
  DashboardSidebarEnvEnvironmentSlugWorkflowsRoute: typeof DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren
  DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute
  DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute: typeof DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute
}

const DashboardSidebarRouteChildren: DashboardSidebarRouteChildren = {
  DashboardSidebarIntegrationsRoute:
    DashboardSidebarIntegrationsRouteWithChildren,
  DashboardSidebarIndexRoute: DashboardSidebarIndexRoute,
  DashboardSidebarEnvEnvironmentSlugActivityFeedRoute:
    DashboardSidebarEnvEnvironmentSlugActivityFeedRoute,
  DashboardSidebarEnvEnvironmentSlugAnalyticsRoute:
    DashboardSidebarEnvEnvironmentSlugAnalyticsRoute,
  DashboardSidebarEnvEnvironmentSlugApiKeysRoute:
    DashboardSidebarEnvEnvironmentSlugApiKeysRoute,
  DashboardSidebarEnvEnvironmentSlugContextsRoute:
    DashboardSidebarEnvEnvironmentSlugContextsRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute:
    DashboardSidebarEnvEnvironmentSlugEnvironmentsRoute,
  DashboardSidebarEnvEnvironmentSlugLayoutsRoute:
    DashboardSidebarEnvEnvironmentSlugLayoutsRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugSubscribersRoute:
    DashboardSidebarEnvEnvironmentSlugSubscribersRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugTopicsRoute:
    DashboardSidebarEnvEnvironmentSlugTopicsRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugTranslationsRoute:
    DashboardSidebarEnvEnvironmentSlugTranslationsRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugWebhooksRoute:
    DashboardSidebarEnvEnvironmentSlugWebhooksRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugWelcomeRoute:
    DashboardSidebarEnvEnvironmentSlugWelcomeRoute,
  DashboardSidebarEnvEnvironmentSlugWorkflowsRoute:
    DashboardSidebarEnvEnvironmentSlugWorkflowsRouteWithChildren,
  DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute:
    DashboardSidebarEnvEnvironmentSlugActivityRequestsRoute,
  DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute:
    DashboardSidebarEnvEnvironmentSlugActivityWorkflowRunsRoute,
}

const DashboardSidebarRouteWithChildren =
  DashboardSidebarRoute._addFileChildren(DashboardSidebarRouteChildren)

interface DashboardRouteChildren {
  DashboardFullpageRoute: typeof DashboardFullpageRouteWithChildren
  DashboardSidebarRoute: typeof DashboardSidebarRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFullpageRoute: DashboardFullpageRouteWithChildren,
  DashboardSidebarRoute: DashboardSidebarRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingInboxRouteChildren {
  OnboardingInboxEmbedRoute: typeof OnboardingInboxEmbedRoute
  OnboardingInboxSuccessRoute: typeof OnboardingInboxSuccessRoute
}

const OnboardingInboxRouteChildren: OnboardingInboxRouteChildren = {
  OnboardingInboxEmbedRoute: OnboardingInboxEmbedRoute,
  OnboardingInboxSuccessRoute: OnboardingInboxSuccessRoute,
}

const OnboardingInboxRouteWithChildren = OnboardingInboxRoute._addFileChildren(
  OnboardingInboxRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingInboxRoute: typeof OnboardingInboxRouteWithChildren
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingInboxRoute: OnboardingInboxRouteWithChildren,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
