/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as OnboardingInboxRouteImport } from './routes/onboarding/inbox'
import { Route as DashboardSidebarRouteImport } from './routes/_dashboard/_sidebar'
import { Route as DashboardFullpageRouteImport } from './routes/_dashboard/_fullpage'
import { Route as DashboardSidebarIndexRouteImport } from './routes/_dashboard/_sidebar/index'
import { Route as OnboardingInboxSuccessRouteImport } from './routes/onboarding/inbox/success'
import { Route as OnboardingInboxEmbedRouteImport } from './routes/onboarding/inbox/embed'
import { Route as DashboardSidebarIntegrationsRouteImport } from './routes/_dashboard/_sidebar/integrations'
import { Route as DashboardSidebarIntegrationsConnectRouteImport } from './routes/_dashboard/_sidebar/integrations/connect'
import { Route as DashboardSidebarEnvironmentSlugWorkflowsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/workflows'
import { Route as DashboardSidebarEnvironmentSlugWelcomeRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/welcome'
import { Route as DashboardSidebarEnvironmentSlugWebhooksRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/webhooks'
import { Route as DashboardSidebarEnvironmentSlugTranslationsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/translations'
import { Route as DashboardSidebarEnvironmentSlugTopicsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/topics'
import { Route as DashboardSidebarEnvironmentSlugSubscribersRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/subscribers'
import { Route as DashboardSidebarEnvironmentSlugLayoutsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/layouts'

import { Route as DashboardSidebarEnvironmentSlugContextsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/contexts'
import { Route as DashboardSidebarEnvironmentSlugApiKeysRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/api-keys'
import { Route as DashboardSidebarEnvironmentSlugAnalyticsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/analytics'
import { Route as DashboardSidebarEnvironmentSlugActivityFeedRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/activity-feed'
import { Route as DashboardSidebarIntegrationsConnectProviderIdRouteImport } from './routes/_dashboard/_sidebar/integrations/connect/$providerId'
import { Route as DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport } from './routes/_dashboard/_sidebar/integrations/$integrationId/update'
import { Route as DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/workflows/templates'
import { Route as DashboardSidebarEnvironmentSlugWorkflowsCreateRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/workflows/create'
import { Route as DashboardSidebarEnvironmentSlugWebhooksLogsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/webhooks/logs'
import { Route as DashboardSidebarEnvironmentSlugWebhooksEventCatalogRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/webhooks/event-catalog'
import { Route as DashboardSidebarEnvironmentSlugWebhooksEndpointsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/webhooks/endpoints'
import { Route as DashboardSidebarEnvironmentSlugWebhooksActivityRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/webhooks/activity'
import { Route as DashboardSidebarEnvironmentSlugTranslationsSettingsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/translations/settings'
import { Route as DashboardSidebarEnvironmentSlugTopicsCreateRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/topics/create'
import { Route as DashboardSidebarEnvironmentSlugSubscribersCreateRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/subscribers/create'
import { Route as DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/subscribers/$subscriberId'
import { Route as DashboardSidebarEnvironmentSlugLayoutsCreateRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/layouts/create'
import { Route as DashboardSidebarEnvironmentSlugContextsCreateRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/contexts/create'
import { Route as DashboardSidebarEnvironmentSlugActivityWorkflowRunsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/activity/workflow-runs'
import { Route as DashboardSidebarEnvironmentSlugActivityRequestsRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/activity/requests'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug'
import { Route as DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/layouts/$layoutSlug'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/index'
import { Route as DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/workflows/templates/$templateId'
import { Route as DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/workflows/duplicate/$workflowId'
import { Route as DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/topics/$topicKey/edit'
import { Route as DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/layouts/duplicate/$layoutId'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/trigger'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/test'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/preferences'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/activity'
import { Route as DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/translations/$resourceType/$resourceId/$locale'
import { Route as DashboardSidebarEnvironmentSlugContextsTypeIdEditRouteImport } from './routes/_dashboard/_sidebar/$environmentSlug/contexts/$type/$id/edit'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/index'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
import { Route as DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport } from './routes/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInboxRoute = OnboardingInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => OnboardingRoute,
} as any)
const DashboardSidebarRoute = DashboardSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFullpageRoute = DashboardFullpageRouteImport.update({
  id: '/_fullpage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSidebarIndexRoute = DashboardSidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSidebarRoute,
} as any)
const OnboardingInboxSuccessRoute = OnboardingInboxSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingInboxRoute,
} as any)
const OnboardingInboxEmbedRoute = OnboardingInboxEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => OnboardingInboxRoute,
} as any)
const DashboardSidebarIntegrationsRoute =
  DashboardSidebarIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarIntegrationsConnectRoute =
  DashboardSidebarIntegrationsConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => DashboardSidebarIntegrationsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWorkflowsRoute =
  DashboardSidebarEnvironmentSlugWorkflowsRouteImport.update({
    id: '/$environmentSlug/workflows',
    path: '/$environmentSlug/workflows',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWelcomeRoute =
  DashboardSidebarEnvironmentSlugWelcomeRouteImport.update({
    id: '/$environmentSlug/welcome',
    path: '/$environmentSlug/welcome',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWebhooksRoute =
  DashboardSidebarEnvironmentSlugWebhooksRouteImport.update({
    id: '/$environmentSlug/webhooks',
    path: '/$environmentSlug/webhooks',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugTranslationsRoute =
  DashboardSidebarEnvironmentSlugTranslationsRouteImport.update({
    id: '/$environmentSlug/translations',
    path: '/$environmentSlug/translations',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugTopicsRoute =
  DashboardSidebarEnvironmentSlugTopicsRouteImport.update({
    id: '/$environmentSlug/topics',
    path: '/$environmentSlug/topics',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugSubscribersRoute =
  DashboardSidebarEnvironmentSlugSubscribersRouteImport.update({
    id: '/$environmentSlug/subscribers',
    path: '/$environmentSlug/subscribers',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugLayoutsRoute =
  DashboardSidebarEnvironmentSlugLayoutsRouteImport.update({
    id: '/$environmentSlug/layouts',
    path: '/$environmentSlug/layouts',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)

const DashboardSidebarEnvironmentSlugContextsRoute =
  DashboardSidebarEnvironmentSlugContextsRouteImport.update({
    id: '/$environmentSlug/contexts',
    path: '/$environmentSlug/contexts',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugApiKeysRoute =
  DashboardSidebarEnvironmentSlugApiKeysRouteImport.update({
    id: '/$environmentSlug/api-keys',
    path: '/$environmentSlug/api-keys',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugAnalyticsRoute =
  DashboardSidebarEnvironmentSlugAnalyticsRouteImport.update({
    id: '/$environmentSlug/analytics',
    path: '/$environmentSlug/analytics',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugActivityFeedRoute =
  DashboardSidebarEnvironmentSlugActivityFeedRouteImport.update({
    id: '/$environmentSlug/activity-feed',
    path: '/$environmentSlug/activity-feed',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarIntegrationsConnectProviderIdRoute =
  DashboardSidebarIntegrationsConnectProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => DashboardSidebarIntegrationsConnectRoute,
  } as any)
const DashboardSidebarIntegrationsIntegrationIdUpdateRoute =
  DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport.update({
    id: '/$integrationId/update',
    path: '/$integrationId/update',
    getParentRoute: () => DashboardSidebarIntegrationsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute =
  DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWorkflowsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWorkflowsCreateRoute =
  DashboardSidebarEnvironmentSlugWorkflowsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWorkflowsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWebhooksLogsRoute =
  DashboardSidebarEnvironmentSlugWebhooksLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute =
  DashboardSidebarEnvironmentSlugWebhooksEventCatalogRouteImport.update({
    id: '/event-catalog',
    path: '/event-catalog',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute =
  DashboardSidebarEnvironmentSlugWebhooksEndpointsRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWebhooksActivityRoute =
  DashboardSidebarEnvironmentSlugWebhooksActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardSidebarEnvironmentSlugWebhooksRoute,
  } as any)
const DashboardSidebarEnvironmentSlugTranslationsSettingsRoute =
  DashboardSidebarEnvironmentSlugTranslationsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardSidebarEnvironmentSlugTranslationsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugTopicsCreateRoute =
  DashboardSidebarEnvironmentSlugTopicsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvironmentSlugTopicsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugSubscribersCreateRoute =
  DashboardSidebarEnvironmentSlugSubscribersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvironmentSlugSubscribersRoute,
  } as any)
const DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute =
  DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRouteImport.update({
    id: '/$subscriberId',
    path: '/$subscriberId',
    getParentRoute: () => DashboardSidebarEnvironmentSlugSubscribersRoute,
  } as any)
const DashboardSidebarEnvironmentSlugLayoutsCreateRoute =
  DashboardSidebarEnvironmentSlugLayoutsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvironmentSlugLayoutsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugContextsCreateRoute =
  DashboardSidebarEnvironmentSlugContextsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardSidebarEnvironmentSlugContextsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute =
  DashboardSidebarEnvironmentSlugActivityWorkflowRunsRouteImport.update({
    id: '/$environmentSlug/activity/workflow-runs',
    path: '/$environmentSlug/activity/workflow-runs',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardSidebarEnvironmentSlugActivityRequestsRoute =
  DashboardSidebarEnvironmentSlugActivityRequestsRouteImport.update({
    id: '/$environmentSlug/activity/requests',
    path: '/$environmentSlug/activity/requests',
    getParentRoute: () => DashboardSidebarRoute,
  } as any)
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteImport.update({
    id: '/$environmentSlug/workflows/$workflowSlug',
    path: '/$environmentSlug/workflows/$workflowSlug',
    getParentRoute: () => DashboardFullpageRoute,
  } as any)
const DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute =
  DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRouteImport.update({
    id: '/$environmentSlug/layouts/$layoutSlug',
    path: '/$environmentSlug/layouts/$layoutSlug',
    getParentRoute: () => DashboardFullpageRoute,
  } as any)
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
  } as any)
const DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute =
  DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport.update(
    {
      id: '/$templateId',
      path: '/$templateId',
      getParentRoute: () =>
        DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute,
    } as any,
  )
const DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute =
  DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport.update(
    {
      id: '/duplicate/$workflowId',
      path: '/duplicate/$workflowId',
      getParentRoute: () => DashboardSidebarEnvironmentSlugWorkflowsRoute,
    } as any,
  )
const DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute =
  DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRouteImport.update({
    id: '/$topicKey/edit',
    path: '/$topicKey/edit',
    getParentRoute: () => DashboardSidebarEnvironmentSlugTopicsRoute,
  } as any)
const DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute =
  DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport.update({
    id: '/duplicate/$layoutId',
    path: '/duplicate/$layoutId',
    getParentRoute: () => DashboardSidebarEnvironmentSlugLayoutsRoute,
  } as any)
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport.update(
    {
      id: '/trigger',
      path: '/trigger',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () =>
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
  } as any)
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport.update(
    {
      id: '/preferences',
      path: '/preferences',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport.update(
    {
      id: '/activity',
      path: '/activity',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute =
  DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport.update(
    {
      id: '/$resourceType/$resourceId/$locale',
      path: '/$resourceType/$resourceId/$locale',
      getParentRoute: () => DashboardSidebarEnvironmentSlugTranslationsRoute,
    } as any,
  )
const DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute =
  DashboardSidebarEnvironmentSlugContextsTypeIdEditRouteImport.update({
    id: '/$type/$id/edit',
    path: '/$type/$id/edit',
    getParentRoute: () => DashboardSidebarEnvironmentSlugContextsRoute,
  } as any)
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport.update(
    {
      id: '/steps/$stepSlug/',
      path: '/steps/$stepSlug/',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport.update(
    {
      id: '/steps/$stepSlug/editor',
      path: '/steps/$stepSlug/editor',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )
const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport.update(
    {
      id: '/steps/$stepSlug/conditions',
      path: '/steps/$stepSlug/conditions',
      getParentRoute: () =>
        DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DashboardSidebarIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/$environmentSlug/activity-feed': typeof DashboardSidebarEnvironmentSlugActivityFeedRoute
  '/$environmentSlug/analytics': typeof DashboardSidebarEnvironmentSlugAnalyticsRoute
  '/$environmentSlug/api-keys': typeof DashboardSidebarEnvironmentSlugApiKeysRoute
  '/$environmentSlug/contexts': typeof DashboardSidebarEnvironmentSlugContextsRouteWithChildren
  '/$environmentSlug/layouts': typeof DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren
  '/$environmentSlug/subscribers': typeof DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren
  '/$environmentSlug/topics': typeof DashboardSidebarEnvironmentSlugTopicsRouteWithChildren
  '/$environmentSlug/translations': typeof DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren
  '/$environmentSlug/webhooks': typeof DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren
  '/$environmentSlug/welcome': typeof DashboardSidebarEnvironmentSlugWelcomeRoute
  '/$environmentSlug/workflows': typeof DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren
  '/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute
  '/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
  '/$environmentSlug/activity/requests': typeof DashboardSidebarEnvironmentSlugActivityRequestsRoute
  '/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute
  '/$environmentSlug/contexts/create': typeof DashboardSidebarEnvironmentSlugContextsCreateRoute
  '/$environmentSlug/layouts/create': typeof DashboardSidebarEnvironmentSlugLayoutsCreateRoute
  '/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute
  '/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvironmentSlugSubscribersCreateRoute
  '/$environmentSlug/topics/create': typeof DashboardSidebarEnvironmentSlugTopicsCreateRoute
  '/$environmentSlug/translations/settings': typeof DashboardSidebarEnvironmentSlugTranslationsSettingsRoute
  '/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvironmentSlugWebhooksActivityRoute
  '/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute
  '/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute
  '/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvironmentSlugWebhooksLogsRoute
  '/$environmentSlug/workflows/create': typeof DashboardSidebarEnvironmentSlugWorkflowsCreateRoute
  '/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute
  '/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/$environmentSlug/workflows/$workflowSlug/': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute
  '/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardSidebarIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/$environmentSlug/activity-feed': typeof DashboardSidebarEnvironmentSlugActivityFeedRoute
  '/$environmentSlug/analytics': typeof DashboardSidebarEnvironmentSlugAnalyticsRoute
  '/$environmentSlug/api-keys': typeof DashboardSidebarEnvironmentSlugApiKeysRoute
  '/$environmentSlug/contexts': typeof DashboardSidebarEnvironmentSlugContextsRouteWithChildren
  '/$environmentSlug/layouts': typeof DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren
  '/$environmentSlug/subscribers': typeof DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren
  '/$environmentSlug/topics': typeof DashboardSidebarEnvironmentSlugTopicsRouteWithChildren
  '/$environmentSlug/translations': typeof DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren
  '/$environmentSlug/webhooks': typeof DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren
  '/$environmentSlug/welcome': typeof DashboardSidebarEnvironmentSlugWelcomeRoute
  '/$environmentSlug/workflows': typeof DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren
  '/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute
  '/$environmentSlug/activity/requests': typeof DashboardSidebarEnvironmentSlugActivityRequestsRoute
  '/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute
  '/$environmentSlug/contexts/create': typeof DashboardSidebarEnvironmentSlugContextsCreateRoute
  '/$environmentSlug/layouts/create': typeof DashboardSidebarEnvironmentSlugLayoutsCreateRoute
  '/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute
  '/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvironmentSlugSubscribersCreateRoute
  '/$environmentSlug/topics/create': typeof DashboardSidebarEnvironmentSlugTopicsCreateRoute
  '/$environmentSlug/translations/settings': typeof DashboardSidebarEnvironmentSlugTranslationsSettingsRoute
  '/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvironmentSlugWebhooksActivityRoute
  '/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute
  '/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute
  '/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvironmentSlugWebhooksLogsRoute
  '/$environmentSlug/workflows/create': typeof DashboardSidebarEnvironmentSlugWorkflowsCreateRoute
  '/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute
  '/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute
  '/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_dashboard/_fullpage': typeof DashboardFullpageRouteWithChildren
  '/_dashboard/_sidebar': typeof DashboardSidebarRouteWithChildren
  '/onboarding/inbox': typeof OnboardingInboxRouteWithChildren
  '/_dashboard/_sidebar/integrations': typeof DashboardSidebarIntegrationsRouteWithChildren
  '/onboarding/inbox/embed': typeof OnboardingInboxEmbedRoute
  '/onboarding/inbox/success': typeof OnboardingInboxSuccessRoute
  '/_dashboard/_sidebar/': typeof DashboardSidebarIndexRoute
  '/_dashboard/_sidebar/$environmentSlug/activity-feed': typeof DashboardSidebarEnvironmentSlugActivityFeedRoute
  '/_dashboard/_sidebar/$environmentSlug/analytics': typeof DashboardSidebarEnvironmentSlugAnalyticsRoute
  '/_dashboard/_sidebar/$environmentSlug/api-keys': typeof DashboardSidebarEnvironmentSlugApiKeysRoute
  '/_dashboard/_sidebar/$environmentSlug/contexts': typeof DashboardSidebarEnvironmentSlugContextsRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/layouts': typeof DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/subscribers': typeof DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/topics': typeof DashboardSidebarEnvironmentSlugTopicsRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/translations': typeof DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/webhooks': typeof DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/welcome': typeof DashboardSidebarEnvironmentSlugWelcomeRoute
  '/_dashboard/_sidebar/$environmentSlug/workflows': typeof DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren
  '/_dashboard/_sidebar/integrations/connect': typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  '/_dashboard/_fullpage/$environmentSlug/layouts/$layoutSlug': typeof DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
  '/_dashboard/_sidebar/$environmentSlug/activity/requests': typeof DashboardSidebarEnvironmentSlugActivityRequestsRoute
  '/_dashboard/_sidebar/$environmentSlug/activity/workflow-runs': typeof DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute
  '/_dashboard/_sidebar/$environmentSlug/contexts/create': typeof DashboardSidebarEnvironmentSlugContextsCreateRoute
  '/_dashboard/_sidebar/$environmentSlug/layouts/create': typeof DashboardSidebarEnvironmentSlugLayoutsCreateRoute
  '/_dashboard/_sidebar/$environmentSlug/subscribers/$subscriberId': typeof DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute
  '/_dashboard/_sidebar/$environmentSlug/subscribers/create': typeof DashboardSidebarEnvironmentSlugSubscribersCreateRoute
  '/_dashboard/_sidebar/$environmentSlug/topics/create': typeof DashboardSidebarEnvironmentSlugTopicsCreateRoute
  '/_dashboard/_sidebar/$environmentSlug/translations/settings': typeof DashboardSidebarEnvironmentSlugTranslationsSettingsRoute
  '/_dashboard/_sidebar/$environmentSlug/webhooks/activity': typeof DashboardSidebarEnvironmentSlugWebhooksActivityRoute
  '/_dashboard/_sidebar/$environmentSlug/webhooks/endpoints': typeof DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute
  '/_dashboard/_sidebar/$environmentSlug/webhooks/event-catalog': typeof DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute
  '/_dashboard/_sidebar/$environmentSlug/webhooks/logs': typeof DashboardSidebarEnvironmentSlugWebhooksLogsRoute
  '/_dashboard/_sidebar/$environmentSlug/workflows/create': typeof DashboardSidebarEnvironmentSlugWorkflowsCreateRoute
  '/_dashboard/_sidebar/$environmentSlug/workflows/templates': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  '/_dashboard/_sidebar/integrations/$integrationId/update': typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
  '/_dashboard/_sidebar/integrations/connect/$providerId': typeof DashboardSidebarIntegrationsConnectProviderIdRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/activity': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/preferences': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/test': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/trigger': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  '/_dashboard/_sidebar/$environmentSlug/layouts/duplicate/$layoutId': typeof DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute
  '/_dashboard/_sidebar/$environmentSlug/topics/$topicKey/edit': typeof DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute
  '/_dashboard/_sidebar/$environmentSlug/workflows/duplicate/$workflowId': typeof DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
  '/_dashboard/_sidebar/$environmentSlug/workflows/templates/$templateId': typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  '/_dashboard/_sidebar/$environmentSlug/contexts/$type/$id/edit': typeof DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute
  '/_dashboard/_sidebar/$environmentSlug/translations/$resourceType/$resourceId/$locale': typeof DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/onboarding/inbox'
    | '/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/$environmentSlug/activity-feed'
    | '/$environmentSlug/analytics'
    | '/$environmentSlug/api-keys'
    | '/$environmentSlug/contexts'
    | '/$environmentSlug/layouts'
    | '/$environmentSlug/subscribers'
    | '/$environmentSlug/topics'
    | '/$environmentSlug/translations'
    | '/$environmentSlug/webhooks'
    | '/$environmentSlug/welcome'
    | '/$environmentSlug/workflows'
    | '/integrations/connect'
    | '/$environmentSlug/layouts/$layoutSlug'
    | '/$environmentSlug/workflows/$workflowSlug'
    | '/$environmentSlug/activity/requests'
    | '/$environmentSlug/activity/workflow-runs'
    | '/$environmentSlug/contexts/create'
    | '/$environmentSlug/layouts/create'
    | '/$environmentSlug/subscribers/$subscriberId'
    | '/$environmentSlug/subscribers/create'
    | '/$environmentSlug/topics/create'
    | '/$environmentSlug/translations/settings'
    | '/$environmentSlug/webhooks/activity'
    | '/$environmentSlug/webhooks/endpoints'
    | '/$environmentSlug/webhooks/event-catalog'
    | '/$environmentSlug/webhooks/logs'
    | '/$environmentSlug/workflows/create'
    | '/$environmentSlug/workflows/templates'
    | '/integrations/$integrationId/update'
    | '/integrations/connect/$providerId'
    | '/$environmentSlug/workflows/$workflowSlug/activity'
    | '/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/$environmentSlug/workflows/$workflowSlug/test'
    | '/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/$environmentSlug/layouts/duplicate/$layoutId'
    | '/$environmentSlug/topics/$topicKey/edit'
    | '/$environmentSlug/workflows/duplicate/$workflowId'
    | '/$environmentSlug/workflows/templates/$templateId'
    | '/$environmentSlug/workflows/$workflowSlug/'
    | '/$environmentSlug/contexts/$type/$id/edit'
    | '/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/onboarding/inbox'
    | '/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/$environmentSlug/activity-feed'
    | '/$environmentSlug/analytics'
    | '/$environmentSlug/api-keys'
    | '/$environmentSlug/contexts'
    | '/$environmentSlug/layouts'
    | '/$environmentSlug/subscribers'
    | '/$environmentSlug/topics'
    | '/$environmentSlug/translations'
    | '/$environmentSlug/webhooks'
    | '/$environmentSlug/welcome'
    | '/$environmentSlug/workflows'
    | '/integrations/connect'
    | '/$environmentSlug/layouts/$layoutSlug'
    | '/$environmentSlug/activity/requests'
    | '/$environmentSlug/activity/workflow-runs'
    | '/$environmentSlug/contexts/create'
    | '/$environmentSlug/layouts/create'
    | '/$environmentSlug/subscribers/$subscriberId'
    | '/$environmentSlug/subscribers/create'
    | '/$environmentSlug/topics/create'
    | '/$environmentSlug/translations/settings'
    | '/$environmentSlug/webhooks/activity'
    | '/$environmentSlug/webhooks/endpoints'
    | '/$environmentSlug/webhooks/event-catalog'
    | '/$environmentSlug/webhooks/logs'
    | '/$environmentSlug/workflows/create'
    | '/$environmentSlug/workflows/templates'
    | '/integrations/$integrationId/update'
    | '/integrations/connect/$providerId'
    | '/$environmentSlug/workflows/$workflowSlug/activity'
    | '/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/$environmentSlug/workflows/$workflowSlug/test'
    | '/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/$environmentSlug/layouts/duplicate/$layoutId'
    | '/$environmentSlug/topics/$topicKey/edit'
    | '/$environmentSlug/workflows/duplicate/$workflowId'
    | '/$environmentSlug/workflows/templates/$templateId'
    | '/$environmentSlug/workflows/$workflowSlug'
    | '/$environmentSlug/contexts/$type/$id/edit'
    | '/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug'
  id:
    | '__root__'
    | '/_dashboard'
    | '/onboarding'
    | '/_dashboard/_fullpage'
    | '/_dashboard/_sidebar'
    | '/onboarding/inbox'
    | '/_dashboard/_sidebar/integrations'
    | '/onboarding/inbox/embed'
    | '/onboarding/inbox/success'
    | '/_dashboard/_sidebar/'
    | '/_dashboard/_sidebar/$environmentSlug/activity-feed'
    | '/_dashboard/_sidebar/$environmentSlug/analytics'
    | '/_dashboard/_sidebar/$environmentSlug/api-keys'
    | '/_dashboard/_sidebar/$environmentSlug/contexts'
    | '/_dashboard/_sidebar/$environmentSlug/layouts'
    | '/_dashboard/_sidebar/$environmentSlug/subscribers'
    | '/_dashboard/_sidebar/$environmentSlug/topics'
    | '/_dashboard/_sidebar/$environmentSlug/translations'
    | '/_dashboard/_sidebar/$environmentSlug/webhooks'
    | '/_dashboard/_sidebar/$environmentSlug/welcome'
    | '/_dashboard/_sidebar/$environmentSlug/workflows'
    | '/_dashboard/_sidebar/integrations/connect'
    | '/_dashboard/_fullpage/$environmentSlug/layouts/$layoutSlug'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug'
    | '/_dashboard/_sidebar/$environmentSlug/activity/requests'
    | '/_dashboard/_sidebar/$environmentSlug/activity/workflow-runs'
    | '/_dashboard/_sidebar/$environmentSlug/contexts/create'
    | '/_dashboard/_sidebar/$environmentSlug/layouts/create'
    | '/_dashboard/_sidebar/$environmentSlug/subscribers/$subscriberId'
    | '/_dashboard/_sidebar/$environmentSlug/subscribers/create'
    | '/_dashboard/_sidebar/$environmentSlug/topics/create'
    | '/_dashboard/_sidebar/$environmentSlug/translations/settings'
    | '/_dashboard/_sidebar/$environmentSlug/webhooks/activity'
    | '/_dashboard/_sidebar/$environmentSlug/webhooks/endpoints'
    | '/_dashboard/_sidebar/$environmentSlug/webhooks/event-catalog'
    | '/_dashboard/_sidebar/$environmentSlug/webhooks/logs'
    | '/_dashboard/_sidebar/$environmentSlug/workflows/create'
    | '/_dashboard/_sidebar/$environmentSlug/workflows/templates'
    | '/_dashboard/_sidebar/integrations/$integrationId/update'
    | '/_dashboard/_sidebar/integrations/connect/$providerId'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/activity'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/preferences'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/test'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/trigger'
    | '/_dashboard/_sidebar/$environmentSlug/layouts/duplicate/$layoutId'
    | '/_dashboard/_sidebar/$environmentSlug/topics/$topicKey/edit'
    | '/_dashboard/_sidebar/$environmentSlug/workflows/duplicate/$workflowId'
    | '/_dashboard/_sidebar/$environmentSlug/workflows/templates/$templateId'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/'
    | '/_dashboard/_sidebar/$environmentSlug/contexts/$type/$id/edit'
    | '/_dashboard/_sidebar/$environmentSlug/translations/$resourceType/$resourceId/$locale'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
    | '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/inbox': {
      id: '/onboarding/inbox'
      path: '/inbox'
      fullPath: '/onboarding/inbox'
      preLoaderRoute: typeof OnboardingInboxRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_dashboard/_sidebar': {
      id: '/_dashboard/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardSidebarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_fullpage': {
      id: '/_dashboard/_fullpage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardFullpageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_sidebar/': {
      id: '/_dashboard/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardSidebarIndexRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/onboarding/inbox/success': {
      id: '/onboarding/inbox/success'
      path: '/success'
      fullPath: '/onboarding/inbox/success'
      preLoaderRoute: typeof OnboardingInboxSuccessRouteImport
      parentRoute: typeof OnboardingInboxRoute
    }
    '/onboarding/inbox/embed': {
      id: '/onboarding/inbox/embed'
      path: '/embed'
      fullPath: '/onboarding/inbox/embed'
      preLoaderRoute: typeof OnboardingInboxEmbedRouteImport
      parentRoute: typeof OnboardingInboxRoute
    }
    '/_dashboard/_sidebar/integrations': {
      id: '/_dashboard/_sidebar/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashboardSidebarIntegrationsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/integrations/connect': {
      id: '/_dashboard/_sidebar/integrations/connect'
      path: '/connect'
      fullPath: '/integrations/connect'
      preLoaderRoute: typeof DashboardSidebarIntegrationsConnectRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/workflows': {
      id: '/_dashboard/_sidebar/$environmentSlug/workflows'
      path: '/$environmentSlug/workflows'
      fullPath: '/$environmentSlug/workflows'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/welcome': {
      id: '/_dashboard/_sidebar/$environmentSlug/welcome'
      path: '/$environmentSlug/welcome'
      fullPath: '/$environmentSlug/welcome'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWelcomeRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/webhooks': {
      id: '/_dashboard/_sidebar/$environmentSlug/webhooks'
      path: '/$environmentSlug/webhooks'
      fullPath: '/$environmentSlug/webhooks'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/translations': {
      id: '/_dashboard/_sidebar/$environmentSlug/translations'
      path: '/$environmentSlug/translations'
      fullPath: '/$environmentSlug/translations'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTranslationsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/topics': {
      id: '/_dashboard/_sidebar/$environmentSlug/topics'
      path: '/$environmentSlug/topics'
      fullPath: '/$environmentSlug/topics'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTopicsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/subscribers': {
      id: '/_dashboard/_sidebar/$environmentSlug/subscribers'
      path: '/$environmentSlug/subscribers'
      fullPath: '/$environmentSlug/subscribers'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugSubscribersRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/layouts': {
      id: '/_dashboard/_sidebar/$environmentSlug/layouts'
      path: '/$environmentSlug/layouts'
      fullPath: '/$environmentSlug/layouts'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugLayoutsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/contexts': {
      id: '/_dashboard/_sidebar/$environmentSlug/contexts'
      path: '/$environmentSlug/contexts'
      fullPath: '/$environmentSlug/contexts'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugContextsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/api-keys': {
      id: '/_dashboard/_sidebar/$environmentSlug/api-keys'
      path: '/$environmentSlug/api-keys'
      fullPath: '/$environmentSlug/api-keys'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugApiKeysRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/analytics': {
      id: '/_dashboard/_sidebar/$environmentSlug/analytics'
      path: '/$environmentSlug/analytics'
      fullPath: '/$environmentSlug/analytics'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugAnalyticsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/activity-feed': {
      id: '/_dashboard/_sidebar/$environmentSlug/activity-feed'
      path: '/$environmentSlug/activity-feed'
      fullPath: '/$environmentSlug/activity-feed'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugActivityFeedRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/integrations/connect/$providerId': {
      id: '/_dashboard/_sidebar/integrations/connect/$providerId'
      path: '/$providerId'
      fullPath: '/integrations/connect/$providerId'
      preLoaderRoute: typeof DashboardSidebarIntegrationsConnectProviderIdRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsConnectRoute
    }
    '/_dashboard/_sidebar/integrations/$integrationId/update': {
      id: '/_dashboard/_sidebar/integrations/$integrationId/update'
      path: '/$integrationId/update'
      fullPath: '/integrations/$integrationId/update'
      preLoaderRoute: typeof DashboardSidebarIntegrationsIntegrationIdUpdateRouteImport
      parentRoute: typeof DashboardSidebarIntegrationsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/workflows/templates': {
      id: '/_dashboard/_sidebar/$environmentSlug/workflows/templates'
      path: '/templates'
      fullPath: '/$environmentSlug/workflows/templates'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/workflows/create': {
      id: '/_dashboard/_sidebar/$environmentSlug/workflows/create'
      path: '/create'
      fullPath: '/$environmentSlug/workflows/create'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/webhooks/logs': {
      id: '/_dashboard/_sidebar/$environmentSlug/webhooks/logs'
      path: '/logs'
      fullPath: '/$environmentSlug/webhooks/logs'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWebhooksLogsRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/webhooks/event-catalog': {
      id: '/_dashboard/_sidebar/$environmentSlug/webhooks/event-catalog'
      path: '/event-catalog'
      fullPath: '/$environmentSlug/webhooks/event-catalog'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWebhooksEventCatalogRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/webhooks/endpoints': {
      id: '/_dashboard/_sidebar/$environmentSlug/webhooks/endpoints'
      path: '/endpoints'
      fullPath: '/$environmentSlug/webhooks/endpoints'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWebhooksEndpointsRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/webhooks/activity': {
      id: '/_dashboard/_sidebar/$environmentSlug/webhooks/activity'
      path: '/activity'
      fullPath: '/$environmentSlug/webhooks/activity'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWebhooksActivityRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/translations/settings': {
      id: '/_dashboard/_sidebar/$environmentSlug/translations/settings'
      path: '/settings'
      fullPath: '/$environmentSlug/translations/settings'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTranslationsSettingsRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugTranslationsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/topics/create': {
      id: '/_dashboard/_sidebar/$environmentSlug/topics/create'
      path: '/create'
      fullPath: '/$environmentSlug/topics/create'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTopicsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugTopicsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/subscribers/create': {
      id: '/_dashboard/_sidebar/$environmentSlug/subscribers/create'
      path: '/create'
      fullPath: '/$environmentSlug/subscribers/create'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugSubscribersCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugSubscribersRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/subscribers/$subscriberId': {
      id: '/_dashboard/_sidebar/$environmentSlug/subscribers/$subscriberId'
      path: '/$subscriberId'
      fullPath: '/$environmentSlug/subscribers/$subscriberId'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugSubscribersRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/layouts/create': {
      id: '/_dashboard/_sidebar/$environmentSlug/layouts/create'
      path: '/create'
      fullPath: '/$environmentSlug/layouts/create'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugLayoutsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugLayoutsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/contexts/create': {
      id: '/_dashboard/_sidebar/$environmentSlug/contexts/create'
      path: '/create'
      fullPath: '/$environmentSlug/contexts/create'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugContextsCreateRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugContextsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/activity/workflow-runs': {
      id: '/_dashboard/_sidebar/$environmentSlug/activity/workflow-runs'
      path: '/$environmentSlug/activity/workflow-runs'
      fullPath: '/$environmentSlug/activity/workflow-runs'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugActivityWorkflowRunsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/activity/requests': {
      id: '/_dashboard/_sidebar/$environmentSlug/activity/requests'
      path: '/$environmentSlug/activity/requests'
      fullPath: '/$environmentSlug/activity/requests'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugActivityRequestsRouteImport
      parentRoute: typeof DashboardSidebarRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug'
      path: '/$environmentSlug/workflows/$workflowSlug'
      fullPath: '/$environmentSlug/workflows/$workflowSlug'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteImport
      parentRoute: typeof DashboardFullpageRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/layouts/$layoutSlug': {
      id: '/_dashboard/_fullpage/$environmentSlug/layouts/$layoutSlug'
      path: '/$environmentSlug/layouts/$layoutSlug'
      fullPath: '/$environmentSlug/layouts/$layoutSlug'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRouteImport
      parentRoute: typeof DashboardFullpageRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/'
      path: '/'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/workflows/templates/$templateId': {
      id: '/_dashboard/_sidebar/$environmentSlug/workflows/templates/$templateId'
      path: '/$templateId'
      fullPath: '/$environmentSlug/workflows/templates/$templateId'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/workflows/duplicate/$workflowId': {
      id: '/_dashboard/_sidebar/$environmentSlug/workflows/duplicate/$workflowId'
      path: '/duplicate/$workflowId'
      fullPath: '/$environmentSlug/workflows/duplicate/$workflowId'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/topics/$topicKey/edit': {
      id: '/_dashboard/_sidebar/$environmentSlug/topics/$topicKey/edit'
      path: '/$topicKey/edit'
      fullPath: '/$environmentSlug/topics/$topicKey/edit'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugTopicsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/layouts/duplicate/$layoutId': {
      id: '/_dashboard/_sidebar/$environmentSlug/layouts/duplicate/$layoutId'
      path: '/duplicate/$layoutId'
      fullPath: '/$environmentSlug/layouts/duplicate/$layoutId'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugLayoutsRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/trigger': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/trigger'
      path: '/trigger'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/trigger'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/test': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/test'
      path: '/test'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/test'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/preferences': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/preferences'
      path: '/preferences'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/preferences'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/activity': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/activity'
      path: '/activity'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/activity'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/translations/$resourceType/$resourceId/$locale': {
      id: '/_dashboard/_sidebar/$environmentSlug/translations/$resourceType/$resourceId/$locale'
      path: '/$resourceType/$resourceId/$locale'
      fullPath: '/$environmentSlug/translations/$resourceType/$resourceId/$locale'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugTranslationsRoute
    }
    '/_dashboard/_sidebar/$environmentSlug/contexts/$type/$id/edit': {
      id: '/_dashboard/_sidebar/$environmentSlug/contexts/$type/$id/edit'
      path: '/$type/$id/edit'
      fullPath: '/$environmentSlug/contexts/$type/$id/edit'
      preLoaderRoute: typeof DashboardSidebarEnvironmentSlugContextsTypeIdEditRouteImport
      parentRoute: typeof DashboardSidebarEnvironmentSlugContextsRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
      path: '/steps/$stepSlug'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
      path: '/steps/$stepSlug/editor'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/editor'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
    '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions': {
      id: '/_dashboard/_fullpage/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
      path: '/steps/$stepSlug/conditions'
      fullPath: '/$environmentSlug/workflows/$workflowSlug/steps/$stepSlug/conditions'
      preLoaderRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRouteImport
      parentRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute
    }
  }
}

interface DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteChildren {
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute
}

const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteChildren: DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteChildren =
  {
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugActivityRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugPreferencesRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTestRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugTriggerRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugIndexRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugConditionsRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugEditorRoute,
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute:
      DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugStepsStepSlugIndexRoute,
  }

const DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren =
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute._addFileChildren(
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteChildren,
  )

interface DashboardFullpageRouteChildren {
  DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute: typeof DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute: typeof DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren
}

const DashboardFullpageRouteChildren: DashboardFullpageRouteChildren = {
  DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute:
    DashboardFullpageEnvironmentSlugLayoutsLayoutSlugRoute,
  DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRoute:
    DashboardFullpageEnvironmentSlugWorkflowsWorkflowSlugRouteWithChildren,
}

const DashboardFullpageRouteWithChildren =
  DashboardFullpageRoute._addFileChildren(DashboardFullpageRouteChildren)

interface DashboardSidebarIntegrationsConnectRouteChildren {
  DashboardSidebarIntegrationsConnectProviderIdRoute: typeof DashboardSidebarIntegrationsConnectProviderIdRoute
}

const DashboardSidebarIntegrationsConnectRouteChildren: DashboardSidebarIntegrationsConnectRouteChildren =
  {
    DashboardSidebarIntegrationsConnectProviderIdRoute:
      DashboardSidebarIntegrationsConnectProviderIdRoute,
  }

const DashboardSidebarIntegrationsConnectRouteWithChildren =
  DashboardSidebarIntegrationsConnectRoute._addFileChildren(
    DashboardSidebarIntegrationsConnectRouteChildren,
  )

interface DashboardSidebarIntegrationsRouteChildren {
  DashboardSidebarIntegrationsConnectRoute: typeof DashboardSidebarIntegrationsConnectRouteWithChildren
  DashboardSidebarIntegrationsIntegrationIdUpdateRoute: typeof DashboardSidebarIntegrationsIntegrationIdUpdateRoute
}

const DashboardSidebarIntegrationsRouteChildren: DashboardSidebarIntegrationsRouteChildren =
  {
    DashboardSidebarIntegrationsConnectRoute:
      DashboardSidebarIntegrationsConnectRouteWithChildren,
    DashboardSidebarIntegrationsIntegrationIdUpdateRoute:
      DashboardSidebarIntegrationsIntegrationIdUpdateRoute,
  }

const DashboardSidebarIntegrationsRouteWithChildren =
  DashboardSidebarIntegrationsRoute._addFileChildren(
    DashboardSidebarIntegrationsRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugContextsRouteChildren {
  DashboardSidebarEnvironmentSlugContextsCreateRoute: typeof DashboardSidebarEnvironmentSlugContextsCreateRoute
  DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute: typeof DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute
}

const DashboardSidebarEnvironmentSlugContextsRouteChildren: DashboardSidebarEnvironmentSlugContextsRouteChildren =
  {
    DashboardSidebarEnvironmentSlugContextsCreateRoute:
      DashboardSidebarEnvironmentSlugContextsCreateRoute,
    DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute:
      DashboardSidebarEnvironmentSlugContextsTypeIdEditRoute,
  }

const DashboardSidebarEnvironmentSlugContextsRouteWithChildren =
  DashboardSidebarEnvironmentSlugContextsRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugContextsRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugLayoutsRouteChildren {
  DashboardSidebarEnvironmentSlugLayoutsCreateRoute: typeof DashboardSidebarEnvironmentSlugLayoutsCreateRoute
  DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute: typeof DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute
}

const DashboardSidebarEnvironmentSlugLayoutsRouteChildren: DashboardSidebarEnvironmentSlugLayoutsRouteChildren =
  {
    DashboardSidebarEnvironmentSlugLayoutsCreateRoute:
      DashboardSidebarEnvironmentSlugLayoutsCreateRoute,
    DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute:
      DashboardSidebarEnvironmentSlugLayoutsDuplicateLayoutIdRoute,
  }

const DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren =
  DashboardSidebarEnvironmentSlugLayoutsRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugLayoutsRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugSubscribersRouteChildren {
  DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute: typeof DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute
  DashboardSidebarEnvironmentSlugSubscribersCreateRoute: typeof DashboardSidebarEnvironmentSlugSubscribersCreateRoute
}

const DashboardSidebarEnvironmentSlugSubscribersRouteChildren: DashboardSidebarEnvironmentSlugSubscribersRouteChildren =
  {
    DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute:
      DashboardSidebarEnvironmentSlugSubscribersSubscriberIdRoute,
    DashboardSidebarEnvironmentSlugSubscribersCreateRoute:
      DashboardSidebarEnvironmentSlugSubscribersCreateRoute,
  }

const DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren =
  DashboardSidebarEnvironmentSlugSubscribersRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugSubscribersRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugTopicsRouteChildren {
  DashboardSidebarEnvironmentSlugTopicsCreateRoute: typeof DashboardSidebarEnvironmentSlugTopicsCreateRoute
  DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute: typeof DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute
}

const DashboardSidebarEnvironmentSlugTopicsRouteChildren: DashboardSidebarEnvironmentSlugTopicsRouteChildren =
  {
    DashboardSidebarEnvironmentSlugTopicsCreateRoute:
      DashboardSidebarEnvironmentSlugTopicsCreateRoute,
    DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute:
      DashboardSidebarEnvironmentSlugTopicsTopicKeyEditRoute,
  }

const DashboardSidebarEnvironmentSlugTopicsRouteWithChildren =
  DashboardSidebarEnvironmentSlugTopicsRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugTopicsRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugTranslationsRouteChildren {
  DashboardSidebarEnvironmentSlugTranslationsSettingsRoute: typeof DashboardSidebarEnvironmentSlugTranslationsSettingsRoute
  DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute: typeof DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute
}

const DashboardSidebarEnvironmentSlugTranslationsRouteChildren: DashboardSidebarEnvironmentSlugTranslationsRouteChildren =
  {
    DashboardSidebarEnvironmentSlugTranslationsSettingsRoute:
      DashboardSidebarEnvironmentSlugTranslationsSettingsRoute,
    DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute:
      DashboardSidebarEnvironmentSlugTranslationsResourceTypeResourceIdLocaleRoute,
  }

const DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren =
  DashboardSidebarEnvironmentSlugTranslationsRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugTranslationsRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugWebhooksRouteChildren {
  DashboardSidebarEnvironmentSlugWebhooksActivityRoute: typeof DashboardSidebarEnvironmentSlugWebhooksActivityRoute
  DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute: typeof DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute
  DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute: typeof DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute
  DashboardSidebarEnvironmentSlugWebhooksLogsRoute: typeof DashboardSidebarEnvironmentSlugWebhooksLogsRoute
}

const DashboardSidebarEnvironmentSlugWebhooksRouteChildren: DashboardSidebarEnvironmentSlugWebhooksRouteChildren =
  {
    DashboardSidebarEnvironmentSlugWebhooksActivityRoute:
      DashboardSidebarEnvironmentSlugWebhooksActivityRoute,
    DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute:
      DashboardSidebarEnvironmentSlugWebhooksEndpointsRoute,
    DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute:
      DashboardSidebarEnvironmentSlugWebhooksEventCatalogRoute,
    DashboardSidebarEnvironmentSlugWebhooksLogsRoute:
      DashboardSidebarEnvironmentSlugWebhooksLogsRoute,
  }

const DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren =
  DashboardSidebarEnvironmentSlugWebhooksRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugWebhooksRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteChildren {
  DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute
}

const DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteChildren: DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteChildren =
  {
    DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute:
      DashboardSidebarEnvironmentSlugWorkflowsTemplatesTemplateIdRoute,
  }

const DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren =
  DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteChildren,
  )

interface DashboardSidebarEnvironmentSlugWorkflowsRouteChildren {
  DashboardSidebarEnvironmentSlugWorkflowsCreateRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsCreateRoute
  DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren
  DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute
}

const DashboardSidebarEnvironmentSlugWorkflowsRouteChildren: DashboardSidebarEnvironmentSlugWorkflowsRouteChildren =
  {
    DashboardSidebarEnvironmentSlugWorkflowsCreateRoute:
      DashboardSidebarEnvironmentSlugWorkflowsCreateRoute,
    DashboardSidebarEnvironmentSlugWorkflowsTemplatesRoute:
      DashboardSidebarEnvironmentSlugWorkflowsTemplatesRouteWithChildren,
    DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute:
      DashboardSidebarEnvironmentSlugWorkflowsDuplicateWorkflowIdRoute,
  }

const DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren =
  DashboardSidebarEnvironmentSlugWorkflowsRoute._addFileChildren(
    DashboardSidebarEnvironmentSlugWorkflowsRouteChildren,
  )

interface DashboardSidebarRouteChildren {
  DashboardSidebarIntegrationsRoute: typeof DashboardSidebarIntegrationsRouteWithChildren
  DashboardSidebarIndexRoute: typeof DashboardSidebarIndexRoute
  DashboardSidebarEnvironmentSlugActivityFeedRoute: typeof DashboardSidebarEnvironmentSlugActivityFeedRoute
  DashboardSidebarEnvironmentSlugAnalyticsRoute: typeof DashboardSidebarEnvironmentSlugAnalyticsRoute
  DashboardSidebarEnvironmentSlugApiKeysRoute: typeof DashboardSidebarEnvironmentSlugApiKeysRoute
  DashboardSidebarEnvironmentSlugContextsRoute: typeof DashboardSidebarEnvironmentSlugContextsRouteWithChildren
  DashboardSidebarEnvironmentSlugLayoutsRoute: typeof DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren
  DashboardSidebarEnvironmentSlugSubscribersRoute: typeof DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren
  DashboardSidebarEnvironmentSlugTopicsRoute: typeof DashboardSidebarEnvironmentSlugTopicsRouteWithChildren
  DashboardSidebarEnvironmentSlugTranslationsRoute: typeof DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren
  DashboardSidebarEnvironmentSlugWebhooksRoute: typeof DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren
  DashboardSidebarEnvironmentSlugWelcomeRoute: typeof DashboardSidebarEnvironmentSlugWelcomeRoute
  DashboardSidebarEnvironmentSlugWorkflowsRoute: typeof DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren
  DashboardSidebarEnvironmentSlugActivityRequestsRoute: typeof DashboardSidebarEnvironmentSlugActivityRequestsRoute
  DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute: typeof DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute
}

const DashboardSidebarRouteChildren: DashboardSidebarRouteChildren = {
  DashboardSidebarIntegrationsRoute:
    DashboardSidebarIntegrationsRouteWithChildren,
  DashboardSidebarIndexRoute: DashboardSidebarIndexRoute,
  DashboardSidebarEnvironmentSlugActivityFeedRoute:
    DashboardSidebarEnvironmentSlugActivityFeedRoute,
  DashboardSidebarEnvironmentSlugAnalyticsRoute:
    DashboardSidebarEnvironmentSlugAnalyticsRoute,
  DashboardSidebarEnvironmentSlugApiKeysRoute:
    DashboardSidebarEnvironmentSlugApiKeysRoute,
  DashboardSidebarEnvironmentSlugContextsRoute:
    DashboardSidebarEnvironmentSlugContextsRouteWithChildren,
  DashboardSidebarEnvironmentSlugLayoutsRoute:
    DashboardSidebarEnvironmentSlugLayoutsRouteWithChildren,
  DashboardSidebarEnvironmentSlugSubscribersRoute:
    DashboardSidebarEnvironmentSlugSubscribersRouteWithChildren,
  DashboardSidebarEnvironmentSlugTopicsRoute:
    DashboardSidebarEnvironmentSlugTopicsRouteWithChildren,
  DashboardSidebarEnvironmentSlugTranslationsRoute:
    DashboardSidebarEnvironmentSlugTranslationsRouteWithChildren,
  DashboardSidebarEnvironmentSlugWebhooksRoute:
    DashboardSidebarEnvironmentSlugWebhooksRouteWithChildren,
  DashboardSidebarEnvironmentSlugWelcomeRoute:
    DashboardSidebarEnvironmentSlugWelcomeRoute,
  DashboardSidebarEnvironmentSlugWorkflowsRoute:
    DashboardSidebarEnvironmentSlugWorkflowsRouteWithChildren,
  DashboardSidebarEnvironmentSlugActivityRequestsRoute:
    DashboardSidebarEnvironmentSlugActivityRequestsRoute,
  DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute:
    DashboardSidebarEnvironmentSlugActivityWorkflowRunsRoute,
}

const DashboardSidebarRouteWithChildren =
  DashboardSidebarRoute._addFileChildren(DashboardSidebarRouteChildren)

interface DashboardRouteChildren {
  DashboardFullpageRoute: typeof DashboardFullpageRouteWithChildren
  DashboardSidebarRoute: typeof DashboardSidebarRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFullpageRoute: DashboardFullpageRouteWithChildren,
  DashboardSidebarRoute: DashboardSidebarRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingInboxRouteChildren {
  OnboardingInboxEmbedRoute: typeof OnboardingInboxEmbedRoute
  OnboardingInboxSuccessRoute: typeof OnboardingInboxSuccessRoute
}

const OnboardingInboxRouteChildren: OnboardingInboxRouteChildren = {
  OnboardingInboxEmbedRoute: OnboardingInboxEmbedRoute,
  OnboardingInboxSuccessRoute: OnboardingInboxSuccessRoute,
}

const OnboardingInboxRouteWithChildren = OnboardingInboxRoute._addFileChildren(
  OnboardingInboxRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingInboxRoute: typeof OnboardingInboxRouteWithChildren
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingInboxRoute: OnboardingInboxRouteWithChildren,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
