export const ROUTES = {
	USECASE_SELECT: "/onboarding/usecase",
	INBOX_USECASE: "/onboarding/inbox",
	INBOX_EMBED: "/onboarding/inbox/embed",
	INBOX_EMBED_SUCCESS: "/onboarding/inbox/success",
	ROOT: "/",
	LOCAL_STUDIO_AUTH: "/local-studio/auth",
	ENV: "/env",
	SETTINGS_ORGANIZATION: "/settings/organization",
	SETTINGS_BILLING: "/settings/billing",
	WORKFLOWS: "/$environmentSlug/workflows",
	TRANSLATION_SETTINGS: "/$environmentSlug/translations/settings",
	EDIT_WORKFLOW: "/$environmentSlug/workflows/$workflowSlug",
	EDIT_WORKFLOW_ACTIVITY:
		"/$environmentSlug/workflows/$workflowSlug/activity",
	TEST_WORKFLOW: "/$environmentSlug/workflows/$workflowSlug/test",
	TRIGGER_WORKFLOW: "/$environmentSlug/workflows/$workflowSlug/trigger",
	WELCOME: "/$environmentSlug/welcome",
	HOME: "/$environmentSlug/home",
	EDIT_WORKFLOW_PREFERENCES: "preferences",
	EDIT_STEP: "steps/$stepSlug",

	EDIT_STEP_TEMPLATE: "steps/$stepSlug/editor",
	EDIT_STEP_CONDITIONS: "steps/$stepSlug/conditions",
	INTEGRATIONS: "/integrations",
	INTEGRATIONS_CONNECT: "/integrations/connect",
	INTEGRATIONS_CONNECT_PROVIDER: "/integrations/connect/$providerId",
	INTEGRATIONS_UPDATE: "/integrations/$integrationId/update",
	API_KEYS: "/$environmentSlug/api-keys",
	ENVIRONMENTS: "/$environmentSlug/environments",
	ACTIVITY_FEED: "/$environmentSlug/activity-feed",
	ACTIVITY_WORKFLOW_RUNS: "/$environmentSlug/activity/workflow-runs",
	ACTIVITY_REQUESTS: "/$environmentSlug/activity/requests",
	ANALYTICS: "/$environmentSlug/analytics",
	LOGS: "/$environmentSlug/requests",
	TEMPLATE_STORE: "/$environmentSlug/workflows/templates",
	WORKFLOWS_CREATE: "/$environmentSlug/workflows/create",
	WORKFLOWS_DUPLICATE: "/$environmentSlug/workflows/duplicate/$workflowId",
	TEMPLATE_STORE_CREATE_WORKFLOW:
		"/$environmentSlug/workflows/templates/$templateId",
	SUBSCRIBERS: "/$environmentSlug/subscribers",
	EDIT_SUBSCRIBER: "/$environmentSlug/subscribers/$subscriberId",
	CREATE_SUBSCRIBER: "/$environmentSlug/subscribers/create",
	WEBHOOKS: "/$environmentSlug/webhooks",
	WEBHOOKS_ENDPOINTS: "/$environmentSlug/webhooks/endpoints",
	WEBHOOKS_EVENT_CATALOG: "/$environmentSlug/webhooks/event-catalog",
	WEBHOOKS_LOGS: "/$environmentSlug/webhooks/logs",
	WEBHOOKS_ACTIVITY: "/$environmentSlug/webhooks/activity",
	TOPICS: "/$environmentSlug/topics",
	TOPICS_CREATE: "/$environmentSlug/topics/create",
	TOPICS_EDIT: "/$environmentSlug/topics/$topicKey/edit",
	CONTEXTS: "/$environmentSlug/contexts",
	CONTEXTS_CREATE: "/$environmentSlug/contexts/create",
	CONTEXTS_EDIT: "/$environmentSlug/contexts/$type/$id/edit",
	LAYOUTS: "/$environmentSlug/layouts",
	LAYOUTS_CREATE: "/$environmentSlug/layouts/create",
	LAYOUTS_DUPLICATE: "/$environmentSlug/layouts/duplicate/$layoutId",
	LAYOUTS_EDIT: "/$environmentSlug/layouts/$layoutSlug",
	TRANSLATIONS: "/$environmentSlug/translations",
	TRANSLATIONS_EDIT:
		"/$environmentSlug/translations/$resourceType/$resourceId/$locale",
} as const;

export const buildRoute = (route: string, params: Record<string, string>) => {
	return Object.entries(params).reduce((acc, [key, value]) => {
		return acc.replace(`$${key}`, value);
	}, route);
};
